### ISSUE TITLE
Return JSON for AJAX requests

### ISSUE THREAD

**Issue by nathanaelphilip** [themosis/framework#113]
Is there a way to return JSON instead of a view when using AJAX?

**Comment by jlambe** [comment]
Hi,
yes you can return JSON data instead of HTML, ... For the PHP part of your code, you'll need to echo your data as JSON using the core PHP function `json_encode` like so:

```php
// Inside my ajax callback
// ...some code
echo(json_encode($data));
wp_die();
```

Your data can be whatever you like.

Then for the JavaScript part, if you are using the jQuery Ajax function, simply specify the `dataType` of returned data as `json`.

**Comment by cdarken** [comment]
I think leveraging Symfony Http Foundation would be a better choice.
Something like this in your controller:
```
return new Symfony\Component\HttpFoundation\JsonResponse($data);
```

**Comment by jlambe** [comment]
This is another approach which works great. But now you make me thinking that it would be great to use a controller class and its method when using AJAX, which currently you can't. When using the Ajax class you can simply use a callback function.

Would be great to define like in routes or view composer a class and its method like `MyClass@method` when using the AJAX.

**Comment by nathanaelphilip** [comment]
@jlambe I think what you‘re talking about would be great.

**Comment by jlambe** [comment]
Similar as #116
