### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#123]
What is the minimum setup to do for running a test? I want to test a class that does a cron job, but I want to run it in the cli so I can speed up the dev (to not be required to always add a cron job, for instance).

**Comment by jlambe** [comment]
You'll need the PHPUnit library. Install it as "require-dev" in your composer.json file or install it globally on your machine.

Writing tests for your class will test the php code that is triggered or is executed by a cron job. I don't think you can test the cron job itself as your class is not responsible for the good execution of the cron job. When writing your tests you have to simulate/define a scenario when your cron job is running and when it's not and test how your class behaves regarding those scenarios.

```php
public function testCronJobIsTriggered()
{
     // Supposing the cron job is running, how the class responds... code
}

public function testCronJobIsNotTriggered()
{
    // Code how the class behaves when there is no cron job...
}
```

I would do it this way. You can also use the `Mockery` library if you need to mock/simulate pseudo PHP classes needed by your own class. Perhaps asks the same question on stackoverflow as well as this is common php questions.

**Comment by cdarken** [comment]
Yeah, the thing is that I needed access to the database, so I needed to "boot" wordpress. But I'm not sure it's possible.

**Comment by jlambe** [comment]
You can run unit tests that access the database. You can follow this official guide to get you started: [https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests](https://github.com/wp-cli/wp-cli/wiki/Plugin-Unit-Tests)

We used this technique to run unit tests but found it very slow to execute even on the cli. I would suggest you to "simulate" the return results from the database and test against it by simply adding an array or mock object on your tests.

If you need core WordPress functions, I suggest you to also add this library built by 10up in order to test your class: [https://github.com/10up/wp_mock](https://github.com/10up/wp_mock)

Hope this helps.

**Comment by cdarken** [comment]
Thanks a lot. I will take a look.
