### ISSUE TITLE
Extract translations from scout files

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#126]
I've tried extracting translation strings from sources, using makepot from wordpress tools, like they say here http://codex.wordpress.org/I18n_for_WordPress_Developers#Using_the_i18n_tools and also using poedit, but the translations used in scout files are not found, I suspect it happens because they're between {{ }} . Any ideas how should I proceed?

**Comment by jlambe** [comment]
Yes, because the view files are not directly used, it's a "compiled" file stored in the "storage" directory. If you intend to translate, currently you have to use classic php tags around translation functions. Poedit don't understand the `{{ }}` and assumes what is between as regular string text.

**Comment by cdarken** [comment]
I found a simple solution:
Step 1: execute `find . -type f -print0 | xargs -0 sed -i '1s/^/<?php/'` in the app/views dir
Step 2: extract strings with poedit/xgettext
Step 3: execute `find . -type f -print0 | xargs -0 sed -i '1s/^<?php//'` in the same dir
Step 4: profit :smile:

**Comment by jlambe** [comment]
Great, will test it! Thanks :smile:

**Comment by solverat** [comment]
I think we should reopen this issue. @cdarken's last post is rather a fix than a solution. :) we need a more common way to translate the scout templates:

```php 
{{ __('registration already saved', THEMOSIS_THEME_TEXTDOMAIN) }}
``` 
is much more beautiful than 
```php 
<?php __('registration already saved', THEMOSIS_THEME_TEXTDOMAIN) ?>
```
because its not really strict. but i think it will not be easy, maybe this is the only way: https://github.com/xinax/laravel-gettext

**Comment by jlambe** [comment]
Hi,
I've just looked into the mentioned repository but it seems you always need to compile blade/scout views in PHP so PoEdit can see the strings to translate. It will be great to tell PoEdit to check for string between double curly braces.
Perhaps provide a wp-cli extension to compile the views and point PoEdit to the temp files for translations.

**Comment by jlambe** [comment]
Will look after this. it seems there is configuration that might be available on POEdit in order to found and translate scout/blade template files.

**Comment by jlambe** [comment]
Alright, I have tested a custom parse for poedit in order to translate both .scout.php and .blade.php template files. Here are the steps to follow in order to configure poedit to parse your views:

1. Open PoEdit and go to **Preferences->Parsers**
2. Add a new parser by clicking on **New** and fill in the following arguments:
    - Language: `Scout/Blade`
    - List of extensions: `*.scout.php, *.blade.php`
    - Parser command: `xgettext --language=Python --add-comments=TRANSLATORS --force-po -o %o %C %K %F`
    - Item in keywords list: `-k%k`
    - Item in input files list: `%f`
    - Source code charset: `--from-code=%c`
3. Click **Accept**

Next tell poedit to open the theme `.po` file located inside the theme `languages` folder. The new theme is using the `THEME_TEXTDOMAIN` constant for the textdomain you defined inside the `theme.config.php` file (previously application.config.php).

Here is a code sample from a basic `hello.scout.php` view file:
```php
<html>
<head>
    @wp_head
</head>
<body>
    <h1>{{ __('Hello', THEME_TEXTDOMAIN) }}</h1>
    @wp_footer
</body>
</html>
```
And renders as in attachment with WordPress language set to "Français (France)" for example.
![gettext_views](https://cloud.githubusercontent.com/assets/1917490/15738692/b537eade-28ac-11e6-85e3-3c4af5dc5f42.png)

**Note:** Go to Preferences of PoEdit and not the preferences of the catalog.
**Note bis:** In order for PoEdit to work correctly, do not forget to add **Source keywords** into the catalog preferences. You can see below my own configuration during the tests.

![poedit](https://cloud.githubusercontent.com/assets/1917490/15738827/6c090fd6-28ad-11e6-83ad-1d0a739647c9.png)

The steps in order to configure PoEdit will be added to the documentation. Enjoy!
