### ISSUE TITLE
Metabox in user profile

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#127]
Is there a way  that I can display a metabox in an user profile? I need a way to attach an image for an user.

**Comment by jlambe** [comment]
Hi, currently there are no shortcuts to do this with the framework. This is planned for the next release: [https://github.com/themosis/framework/issues/61](https://github.com/themosis/framework/issues/61)

You'll need to use default WordPress user meta functions in order to do so:
[https://codex.wordpress.org/Function_Reference/add_user_meta](https://codex.wordpress.org/Function_Reference/add_user_meta)

**Comment by cdarken** [comment]
Yeah, but by default there's no nice way to add a media chooser. I will try to use https://github.com/WebDevStudios/CMB2, they have a way  to add metaboxes to user profile.
