### ISSUE TITLE
More control on routes

### ISSUE THREAD

**Issue by davidemorotti** [themosis/framework#131]
Hi,

Although I understand the routing logics of Themosis, I need more control about URLs.

As an example on my project I need to create a File Management section, like Dropbox, but where the folder are the posts title and files are the attachments of each posts. To view the folder lists (posts list) I navigate to the following URL:
http://example.com/media

All fine, I created a new route and a new blank WordPress page called "Media":
```Route::get('page', array('media', 'uses' => 'MediaController@index'));```

But now the problem, when I click on a folder (post), I would like to navigate to a URL like the following:
http://example.com/media/post_name/

On that URL, I would call the `MediaController@show` method, but I can't find the right way to handle with that type of route.

I have to admit that I could be influenced by others PHP frameworks out there, but I think this is a feature a lot of people can't live without.

Any ideas? I would appreciate any suggestions.

Best regards,
Davide

**Comment by jlambe** [comment]
Hi,

first thing to keep in mind that it is still WordPress development. Themosis just brings a code structure.

Now, indeed it seems you're influenced by other PHP frameworks. To resolve your issue, you don't need a page called `media` in order to get a list of posts (folders). The solution is to use a custom post type.

Create a file inside the `admin` folder with the following code:
```php
PostType::make('media', 'Medias', 'Media')->set([
    'public'    => true
]);
```
The first parameter is a the custom post type slug and it is used by default to build the URI like so: `http://example.com/media/`. This URL will get you a list of all posts for the media custom post type.

> Note: Check if `media` is not a reserved keyword for WordPress. If so, create any slug you want and define a custom rewrite slug. Check for the `rewrite` parameter in the docs: https://codex.wordpress.org/Function_Reference/register_post_type

Then simply create individuals posts from your custom post type. If we add a media post with a title of `pictures`, its URI will be: `http://example.com/media/pictures/` and inside this URI you write your query to get attachments.

More information about the `PostType` helper class: http://framework.themosis.com/docs/posttype/

Consider custom post type as a collection of any data. Let me know if it solved your issue.

**Comment by davidemorotti** [comment]
Hi,

thank you for the fast reply and for have brought Themosis to the world!
I think I have to definitively rethink my Problem in a WordPress way.

I'm already working with a custom `PostType`, mine was just a simplified example.

Actually this is not a real issue, so I'm closing the thread. Anyway, thank you for your time!

**Comment by davidemorotti** [comment]
Any chance to get my logic work with [add_rewrite_rule()](https://codex.wordpress.org/Rewrite_API/add_rewrite_rule) functions?

**Comment by jlambe** [comment]
Check this Todo Application built with WordPress and the framework, there is an example with working `add_rewrite_rule` function:https://github.com/themosis/todo/blob/master/htdocs/content/themes/tasks/app/admin/tasks.php

**Comment by treestones** [comment]
Thank you!

**Comment by davidemorotti** [comment]
Thank you!
