### ISSUE TITLE
Test suites

### ISSUE THREAD

**Issue by caiovaccaro** [themosis/framework#134]
Hi @jlambe ,

There is any ready test suite so I can see how you want to do it?

Thanks.

**Comment by jlambe** [comment]
Hi,

the dev branch has currently new dev-dependencies setup in composer.json. The default test suite is called `themosis` but not much tests have been written.

Regarding previous version of PHPUnit setup, we don't require WordPress to be loaded. Using the `wp-mock` library, we expect WordPress functions to be called in order to pass the tests. Personnaly, I still have a lot to learn for unit-testing so if you have any suggestions, I'm all ears :)

Thanks

**Comment by caiovaccaro** [comment]
I'll give it a try, let's see what happens!

**Comment by jlambe** [comment]
The master branch has the tests correctly defined. But you still need to install the test suite from WordPress by looking at wp-cli documentation.
