### ISSUE TITLE
Asset::add on multisite with domain mapping

### ISSUE THREAD

**Issue by cdarken** [themosis/framework#137]
I'm using WordPress MU Domain Mapping (https://wordpress.org/plugins/wordpress-mu-domain-mapping) to map my multisite install to domains. But when I access a subdomain with the mapped domain, the asset path is using the main site domain. Somehow the assets enqueued by wordpress such as jquery work correctly.

**Comment by cdarken** [comment]
Did a little debugging and it looks that's the way WordPress returns it when calling `get_template_directory_uri`.

**Comment by jlambe** [comment]
Will test it, I currently have a multisite instance. The Asset API is looking after registered `assets` folders in order to locate the files and load them. In order to build the URL to the assets, the asset class use this path setup inside the `functions.php` file of the theme:
```php
$paths['app'] = __DIR__.DS.'app'.DS;
```
then register the assets directory by calling this filter:
```php
/*----------------------------------------------------*/
// Register theme asset paths.
/*----------------------------------------------------*/
add_filter('themosisAssetPaths', function($paths)
{
    $paths[THEMOSIS_ASSETS] = themosis_path('app').'assets';
    return $paths;
});
```
I suspect then the `$paths['app']` to not work when using the multisite feature or at least on sub-domain installation.

**Comment by cdarken** [comment]
Actually I think it's the constant THEMOSIS_ASSETS that's wrong, because that one contains the url.

**Comment by jlambe** [comment]
Yes you're right, I've ignored that the constant is used as a key for the URL. Will probably have to check the `network_site_url` function but again not sure there won't be a mapping issue: [https://codex.wordpress.org/Function_Reference/network_site_url](https://codex.wordpress.org/Function_Reference/network_site_url)

Can you posts the URLs you get in your multisite installation as a reference?

**Comment by cdarken** [comment]
I can't post the actual URLs as they are not yet public, but it's something like this:
Main site http://main-domain.com/
assets: http://main-domain.com/content/themes/themosis/app/assets/js/functions.js
Secondary site: http://secondary-domain.com
assets: http://main-domain.com/content/themes/themosis/app/assets/js/functions.js
The problem is mainly with fonts, as requesting them qualifies as cross site requests. Fixed it with mod_headers for now.

**Comment by jlambe** [comment]
@cdarken This issue is currently solved for subdomain multisite installation. The fix is located inside the themosis/theme dev branch actually. I need to test the code against subfolder installation before closing this issue. Will keep you updated when code is release under master branch so you can test it.

**Comment by jlambe** [comment]
Resolved.

**Comment by cdarken** [comment]
Thanks, I will take a look at it.

**Comment by pagegwood** [comment]
@jlambe sorry to dredge up a closed topic, but I believe this issue now exists in the 2.x version of the framework. Can you confirm?
