### ISSUE TITLE
Is there a way to upload multiple image on frontend

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#153]
Hi! is there a way to upload multiple files / images in frontend using the Form::
Or maybe a way to call the media manager on the front end using themosis form.

**Comment by jlambe** [comment]
Hi,

yes you can. Simply add the `enctype='multipart/form-data'` attribute the `<form>` tag. You can create the form as usual with straight html or using the framework `Form::open()` method.

```php
{{ Form::open('', 'post', false, ['enctype' => 'multipart/form-data']); }}
```
Then create `<input type="file">` tags in order to accept file uploads. As for the form tag, you can create the file input with straight html or by using the framework `Form::input('file')` method.

```php
{{ Form::input('file', 'files[]'); }}
```
More information: http://framework.themosis.com/docs/form/

Currently I haven't found a way to load the media manager in front-end. If there is a way, not sure you want all users to see all uploaded files, you'll need to find a way to filter attachments per user.

**Comment by jlambe** [comment]
Unfortunately the WordPress media uploader is not available on front-end. Currently you have to manually create your upload widget for the front-end and use core WP_Image_Editor class to manage your uploads.

@rovillesarate For information: all master branches contains the stable code for release 1.2.0 of the framework if you want to test. Note if you use it with a classic WordPress installation, you need to create a `storage` folder inside `wp-content`. And a `views` directory inside the `storage` one. Else nothing to do. Also note that documentation is not yet written but will be available for public release soon ;)
