### ISSUE TITLE
Unable to activate WP Plugin

### ISSUE THREAD

**Issue by noxify** [themosis/framework#158]
Hi,

I have a problem while activation a plugin which I have downloaded from the WP Plugin Installer (via WP Admin).

My Environment:
* OSX
* MAMP with PHP 5.6.2 
* Latest Themosis (installed via composer)
* Tested Plugin: Paid Memberships Pro

Download of the plugin was successful and it will be shown in my finder under `htdocs/content/plugins`.

But if I click now on "Activate" I will get the following error message:

```
Unhandled Exception

Message:

Undefined offset: 1
Location:

/Applications/MAMP/htdocs/rs-mvc/htdocs/cms/wp-admin/includes/upgrade.php on line 1986
Stack Trace:

#0 /Applications/MAMP/htdocs/rs-mvc/htdocs/content/themes/themosis-theme/functions.php(232): Themosis\Error\Error::native(8, 'Undefined offse...', '/Applications/M...', 1986)
#1 /Applications/MAMP/htdocs/rs-mvc/htdocs/cms/wp-admin/includes/upgrade.php(1986): {closure}(8, 'Undefined offse...', '/Applications/M...', 1986, Array)
#2 /Applications/MAMP/htdocs/rs-mvc/htdocs/content/plugins/paid-memberships-pro/includes/upgradecheck.php(505): dbDelta('\n\t\tCREATE TABLE...')
#3 /Applications/MAMP/htdocs/rs-mvc/htdocs/content/plugins/paid-memberships-pro/includes/upgradecheck.php(68): pmpro_db_delta()
#4 /Applications/MAMP/htdocs/rs-mvc/htdocs/content/plugins/paid-memberships-pro/paid-memberships-pro.php(93): pmpro_checkForUpgrades()
#5 /Applications/MAMP/htdocs/rs-mvc/htdocs/cms/wp-admin/plugins.php(153): include('/Applications/M...')
#6 /Applications/MAMP/htdocs/rs-mvc/htdocs/cms/wp-admin/plugins.php(155): plugin_sandbox_scrape('paid-membership...')
#7 {main}
```

I have tested it also with a standalone version of WP (4.2.2) and there I was able to activate the plugin.

Any idea?

Thanks

**Comment by jlambe** [comment]
Hi,

the application triggered an error message 'cause of an error found in the plugin upgrade process. The plugin is probably giving a non-defined value to a core upgrade function as the message said it is found in core `upgrade.php` file.

By default, the `local` environment will display all errors so this message is normal. In order to hide these messages, simply set to `0` the `THEMOSIS_ERROR_REPORT` constant located in your `config/environments/local.php` file (from the root of your project).

Perhaps this error is only triggered on plugin activation. Reset the error report constant once your plugin is activated so you can catch other errors during local development.

**Comment by noxify** [comment]
Awesome!!!!

Thanks @jlambe you saved my day :)

It works now :)

Short update to my first post:
I have removed the plugin which I have downloaded via WP Plugin Page and added 

```
"wpackagist-plugin/paid-memberships-pro": "dev-trunk"
```

To the composer.json 

Thanks & Closed

**Comment by jlambe** [comment]
:+1:
