### ISSUE TITLE
Multisite wp-admin/cms issue

### ISSUE THREAD

**Issue by AVert** [themosis/framework#181]
I'm install wp multisite as in http://framework.themosis.com/docs/multisite/
this manual. Its work!
But paths in Network admin still is incorect
missed /cms part between sitename and /wp-admin 
Please provide correct way to fix it..
may be not correct but fix it please

**Comment by jlambe** [comment]
On my tests, when you log into the main site, you get the `cms/wp-admin` URI and in fact, when switching to another website of the network the URI change to `wp-admin` only.
Both URI are working correctly.

Now, I'm not sure the issue is from the framework as there are no changes on WordPress itself excepts a custom folder structure which is handled by WordPress anyway.

WordPress release 4.3 has a lot of work/fix for the multisite/network feature of WordPress. Currently I'll wait for release 4.3 before looking into this which seems a core WordPress issue.
