### ISSUE TITLE
Having issues with the wordpress importer plugin

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#182]
Hi! I cant seem to be able to use the wordpress importer with themosis.

I am getting the following issues

Strict Standards: Redefining already defined constructor for class WXR_Parser_Regex in /var/www/rosariocollege/htdocs/content/plugins/wordpress-importer/parsers.php on line 408

Strict Standards: Declaration of WP_Import::bump_request_timeout() should be compatible with WP_Importer::bump_request_timeout($val) in /var/www/rosariocollege/htdocs/content/plugins/wordpress-importer/wordpress-importer.php on line 38

**Comment by jlambe** [comment]
It seems the WordPres importer plugin has bugs. Try to remove the error report by setting the `ERROR_REPORT` value to `0` in your `config/environments/local.php`.

**Comment by rovillesarate** [comment]
Im still getting the same error! =(

**Comment by rovillesarate** [comment]
Its working now. Thanks!

**Comment by proitservice** [comment]
The solution that I would recommend is to temporary downgrade PHP from v7.x. to v5.x. I've just tried that on a project of mine because I was getting 2 warnings and a fatal error and the content wasn't imported in full. After downgrading PHP from v7.1.22 to v5.6.38 I was able to import all the content properly.
