### ISSUE TITLE
Allow other plugin to bind service / igniter

### ISSUE THREAD

**Issue by jofrysutanto** [themosis/framework#191]
Is there a way for external plugin to register bindings?

Been having to add my own `apply_filters` into `bootstrap/start.php` in order to do this. Am I missing something?

What i did: 

```
/*----------------------------------------------------*/
// Register Core Igniter services
/*----------------------------------------------------*/
$app->registerCoreIgniters();

// Allow other plugins to register igniter
apply_filters('themosis_additional_bindings', $app);

/*----------------------------------------------------*/
// Set application configurations.
/*----------------------------------------------------*/
do_action('themosis_configuration');
```

**Comment by jlambe** [comment]
Hi,
this won't work. Currently I haven't opened the API to register other bindings. I know this is a much requested feature but this will come for release 1.2.1 normally.

Actually, you can't pass your bindings through the `registerCoreIgniters()` method. Perhaps if you feel comfortable enough, you could fork the framework and update the `Themosis\Core\Application` class in order to register other bindings?

Going through a WordPress filter might be a good start for plugin developers to bootstrap their classes inside their plugin.

**Comment by jofrysutanto** [comment]
That's okay.

I have been able to register the bindings by passing `$app` through filter to my class:

```
// in themosis/bootstrap/start.php
// Allow other plugins to register igniter
apply_filters('themosis_additional_bindings', $app);

// .. 
// .. in my plugin
/**
 * Load the main class.
 */
add_filter('themosis_register_bindings', function ($app)
{
	$app->register('\TrueFrame\Helpers\LibIgniterService');
	$app->alias('true.lib', '\TrueFrame\Helpers\Lib');
});
```

Seems to be working well, just need to make sure i can easily merge that line back everytime I pull from here.

Cheers.

**Comment by jlambe** [comment]
Nice! Will test this. For release 1.2.1, I intend to provide a plugin boilerplate structure and this will be a great addition in order to easily build plugins for WordPress.
