### ISSUE TITLE
How do you install a themosis made plugin into an existing WP Site?

### ISSUE THREAD

**Issue by otherjohn** [themosis/framework#201]
Perhaps I am looking at this wrong, but can I create a plugin with themosis (just a plugin) and have it sit inside the standard WP wp-content/plugins folder? If so, how do you package it that way?

**Comment by jlambe** [comment]
Currently you need to run your plugin after the `themosis_bootstrap` action hook in order to use the framework classes. Note that this will change for next release.

If you develop a plugin for specific project, simply write your code as a classic WordPress plugin and place it under the `htdocs/content/plugins` directory. Then if you want to re-use it, define a composer.json file at its root and set its type to `"type": "wordpress-plugin"`. Then publish it on packagist.org so you can re-use it on other projects.

By specifying its type as `wordpress-plugin`, composer will automatically install it in the right folder. You can also specify to place it under the `mu-plugins` directory if you want but you'll need to manually require its bootstrap file.

**Comment by otherjohn** [comment]
Thanks for the reply,
What I am concerned about is having to move an existing wordpress install into the htdocs/cms folder. 
Is it possible to have wordpress outside this structure?

**Comment by jlambe** [comment]
"In theory", it's quite straight to move everything. You only need to move your plugins, your theme and the uploads folder.
So you have an existing project set. On another directory (external to your current project), you install a new Themosis project with defaults. This will set up:
- WordPress
- The content directory where you'll put your plugins, theme and uploads
- Install the framework plugin (that you can use or not)
- Install a  basic theme structure and its files (that you can delete if you don't want to refactor your existing theme).

Once this is done, you simply copy/paste your existing project plugins to the new `content/plugins` folder, then move your existing theme to `content/themes` and finally copy/paste the entire `uploads` directory inside the `content` folder.

Finally, setup the `.env.{$env}.php` file to connect to your existing project database and you're all set.

These are the steps if you want to use the themosis framework structure. If you still need/want to keep classic WordPress structure and use some classes of the framework plugin, simply download the zip file here on Github and place it under your plugins or mu-plugins directory.

Hope this helps.

**Comment by otherjohn** [comment]
Thanks, that's the answer I was looking for.
