### ISSUE TITLE
Best Way to extends some Themosis Class

### ISSUE THREAD

**Issue by Cezarion** [themosis/framework#210]
Hello, 

Which way your recommend to extends some class ?
I would like to make a better validation workflow and in particular create notifications in the admin panel. 

Your explanation will be great. 

Thanks a lot

**Comment by jlambe** [comment]
You could directly fork a copy of the `themosis/framework` and make a pull request with your changes in order to add notifications. As this is a requested feature.

You can otherwise create your own classes for validation and notification and load it as a package.

Or as packaged plugin and load it as a WordPress plugin.

If your code is depending on framework classes, bootstrap it using the  `themosis_bootstrap` action hook. Note this is going to change for release 1.2.0.

**Comment by Cezarion** [comment]
Thank's a lot for your response. 
I'm going to explore this ways.
