### ISSUE TITLE
re-register of enqueued js-files

### ISSUE THREAD

**Issue by solverat** [themosis/framework#217]
Hi,

in some cases, registered js-files won't be added. for an example woocommerce - on a single variable product page:

```php
// Enqueue variation scripts
wp_enqueue_script( 'wc-add-to-cart-variation' );
```
But this file will never be loaded. I think its a similar problem like this one: https://github.com/gantry/gantry5/issues/853

> "The issue is that when WooCommerce tries to enqueue wc-add-to-cart-variation script, it's not even registered yet, thus there's nothing to enqueue."

So i have to re-register the script - not that pretty. Do you have any ideas how we can fix that?

**Comment by jlambe** [comment]
Normally for the JS file to be registered with the `wp_enqueue_script` function, they need to provide the url to the script as a parameter as well. The code above only works if `wp_register_script` function has been already called with the same script handle.

Looking at the forum thread, the fix is to pass the URL to the JS asset. This seems to be an issue with WooCommerce as the same error appears on other commercial themes.
