### ISSUE TITLE
Selector to display only certain custom fields

### ISSUE THREAD

**Issue by tomhking** [themosis/framework#225]
Is there a way I can set a selector field to only display certain fields that apply to it? Thank you!

**Comment by jlambe** [comment]
I don't understand what you're trying to achieve. Are you talking about the select field `Field::select()` ?

Or perhaps talking about conditional fields? Like check a checkbox which display another custom field?

**Comment by tomhking** [comment]
So, for example, if write the following:
	Field::select('blocktype', array(
		array(
			'1' => 'None',
			'2' => 'Media',
			'3' => 'Text'
		)
	),
	false, array('title' => 'Block Type')),

	Field::text('blocktype_videoid', array(
		'title' => 'Video ID',
	)),
	Field::media('blocktype_img', array(
		'title' => 'Image',
		'info' => 'Image featured on this block (x recommended)',
		'type' => 'image',
	)),
	Field::editor('blocktype_copy',
		$settings = array(
			'media_buttons' => false,
			textarea_rows' => 10,
		),
		$extras = array(
			'title' => 'Text Block: Copy',
	)),

By default I would like for the option 'None' to only display the 'Field::select'. However, if Media is selected, only the 'Field::text' and the 'Field::media' below that will display; and if Text were selected, the 'Field::editor' would display and the others would be hidden.

I image this would require some jQuery .show and .hide, possibly?

**Comment by jlambe** [comment]
Yes, you need to use javascript for this. With release 1.1.3, you can pass a custom class to your fields. For info, on release 1.2.0, you'll be able to define any attributes ...

Define a 'class' key to the $extras properties of your field so you can select your fields in JS. Use a `change` event on the select field and check the `selected` value in order to display the other fields.

Using the Asset API, you can easily load your css and js files to handle this.

**Comment by tomhking** [comment]
Fantastic, thank you! Is there an example of this in the documentation by chance?

**Comment by jlambe** [comment]
Check the asset documentation on the website: http://framework.themosis.com for details. Also look at the `Set a custom class attribute for "input" fields.` section in the field doc.
