### ISSUE TITLE
How to use markdown on themosis templates

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#226]
Hi! How do you add markdown inside the themosis views templates?

**Comment by jlambe** [comment]
We use this PHP package:
- https://packagist.org/packages/michelf/php-markdown

Also, the docs are written in markdown. If you want to use markdown from the WordPress Editor, you should also de-activate the tinymce editor for your post type in order to avoid auto paragraph, ...

We use it for the documentation website. Here you can see the code where we output the docs in a view:
- https://github.com/themosis/website/blob/master/htdocs/content/themes/themosis/resources/views/pages/docs.scout.php#L13

**Comment by rovillesarate** [comment]
Hi! Already required it at composer and disabled editor from the user but its still not working. Do i need to load it manually or does the composer auto load it already? What about using it directly from the template view? but for now i need to make it work even from the content editor.

**Comment by rovillesarate** [comment]
Already load it by

	"require": {
		"php": ">=5.4",
		"johnpbloch/wordpress": ">=4.1",
		"themosis/framework": "1.1.*",
		"themosis/theme": "1.1.*",
		"michelf/php-markdown": "~1.5.0"
	},

Disable the visual editor when writing from the user profile

called it from the loop
		@loop
		<?php $content = the_content(); ?>
		@include('partials.markdown', array('content' => $content))
		@endloop

the markdown template
    if (class_exists('\Michelf\MarkdownExtra'))
    {
        $html = \Michelf\MarkdownExtra::defaultTransform( $content );
        // $output = do_shortcode(str_replace('<pre>', '<pre class="prettyprint">', $html));
        echo($html);
    }

but still displaying
# Test 1
## Test 2

**Comment by rovillesarate** [comment]
Still displaying the "##

**Comment by jlambe** [comment]
It's autoloaded by composer already. Otherwise you'll get an error for a class not found.

Watch out that `the_content()` function is echoing your content. Use either `Loop::content()  or `get_the_content()` function.

**Comment by rovillesarate** [comment]
Got it working now. Silly me. I was using the_content() instead of get_the_content().

Thank you!
