### ISSUE TITLE
How do we implement Route filters and Route Caching like the one in laravel?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#233]
Hi! Do we already have this feature right now or will it be included to upcoming versions?
It will be helpful if we are also able to cache a whole page and just update the cache if the page has already been updated.

**Comment by jlambe** [comment]
Route filters or middlewares are planned for future release. But a great way to handle this now is by using controllers and use the class __construct method to run some code before the route method is called.

Regarding Cache, it's already there. Did you forget you use WordPress? :) There are cache functions for instant memory cache during a request or there is the Transient API which will store it by default in the database for persistence against a defined duration.

Now, if you use a cache third party tool like Redis, and everything is configured and running, WordPress will use it automatically with its core functions. So no need to update your code if you want to change your cache storage engine.

In order to use redis, there is a plugin from pantheon which provides the file to add in WordPress to configure it. But note you need to have the redis php extension installed in order to make it work.
