### ISSUE TITLE
How do you extend the field factory and create your own field types?

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#238]
Hi! How do you make your own types of fields? I tried extending the field factory class from the theme by creating a namespace for addons.
![image](https://cloud.githubusercontent.com/assets/2109352/11418037/1d64d792-9457-11e5-938a-0144c0d6023b.png)
Here is the folder structure that i made.
![image](https://cloud.githubusercontent.com/assets/2109352/11418066/540fec00-9457-11e5-94ff-68e630b288e7.png)
Then I tried to extend the class of field factory
![image](https://cloud.githubusercontent.com/assets/2109352/11418073/673da5ec-9457-11e5-947c-c6fb1eeb7fc2.png)
Then made a copy of checkbox field structure for my toggle field
![image](https://cloud.githubusercontent.com/assets/2109352/11418100/a0351fba-9457-11e5-91f2-e2ca85efd31d.png)

I cant seem to make it work. Trying to use it in admin page options.
![image](https://cloud.githubusercontent.com/assets/2109352/11418114/c8caba52-9457-11e5-85ba-1f58782d841f.png)
What is the correct way of doing this? Hope you can help me. Thanks!

**Comment by jlambe** [comment]
You don't need to extend the FieldFactory. In order to register a new custom field, you have to use the `make` method on the Field class:
```php
Field::make('\Your\Field\ClassName', $arrayOfProperties);
```

In the above code, the `\Your\Field\ClassName` is your custom class to create a new field. In your case your `Addons\Field\Fields\ToggleField` class.

Now your class has to implement the `IField` interface and extend the `FieldBuilder` class. Make sure to import these.

Next, your class need three methods: `metabox()`, `page()`, `user()` so your custom field can be used in metabox, custom page or user contexts. Each method simply return a custom view where you define the layout of your field. I suggest you to look at the `\Themosis\Field\Fields\TextField` class and its view to see how to build your field: https://github.com/themosis/framework/blob/master/src/Themosis/Field/Fields/TextField.php

Also note that your "$arrayOfProperties" for your custom field class need at least a key called `name` which will hold the input/field name attribute. Core fields use other properties like `features` and `atts` which are used in the field view. Create them if you need or add your custom properties as well.

Finally, inside your class, define the `fieldType()` method. In this method, you have to define the type (attribute) of input where you will store your field value. In case of a toggle field, it might be an `hidden` input. To better understand this, check the framework `Media` field: https://github.com/themosis/framework/blob/master/src/Themosis/Field/Fields/MediaField.php. The UI for the media field is custom but the field value is stored in an input of type `hidden`.

**Comment by rovillesarate** [comment]
What do you mean by "Now your class has to implement the IField interface and extend the FieldBuilder class. Make sure to import these."
![image](https://cloud.githubusercontent.com/assets/2109352/11419916/80347630-9465-11e5-8357-f879c0ca004a.png)
I have already defined the ToggleField field type and also include the metabox(), page(), user().

I just dont get the part where i need to implement IField interface and extend the FieldBuilder?
![image](https://cloud.githubusercontent.com/assets/2109352/11419964/e5bb91e6-9465-11e5-8461-aee296581bda.png)
Do i need to copy the FieldBuilder class or 
![image](https://cloud.githubusercontent.com/assets/2109352/11419991/fffd4db0-9465-11e5-87d2-ccb038e27ff7.png)
It cant seem to find FieldBuilder
Do i need to

use Themosis\Field\Fields\FieldBuilder; ?

**Comment by rovillesarate** [comment]
![image](https://cloud.githubusercontent.com/assets/2109352/11420107/cb474a2a-9466-11e5-9289-5273d380a8e9.png)

I have already include iField and FieldBuilder but I am getting an error
![image](https://cloud.githubusercontent.com/assets/2109352/11420114/d90d6fae-9466-11e5-9003-96e2b2db5414.png)
I have already include a name key on the property but its not working.
![image](https://cloud.githubusercontent.com/assets/2109352/11420139/164f7f24-9467-11e5-8e12-25eb2cead56b.png)

**Comment by jlambe** [comment]
Also import the `use Themosis\View\ViewFactory` inside your ToggleField class. The ViewFactory cast type you have in your __construct method is the Themosis framework one not a ViewFactory created in your namespace.

Or you have to define yours and tell it to extend the core `Themosis\View\ViewFactory`.

**Comment by rovillesarate** [comment]
I am getting another error 
![image](https://cloud.githubusercontent.com/assets/2109352/11420320/58827dd2-9468-11e5-8a24-ffb38135feb3.png)

**Comment by jlambe** [comment]
This one is in your field view file. There is no method `toggle` on the core Form class. You have to built your own html for your field. Check the docs for all methods available in the form class: http://framework.themosis.com/docs/form/

Also, if you want to use the core `title` feature in order to define a readable display title for your field, add the `title` property to `features` key in your $arrayOfProperties.

```php
Field::make('Addons\Field\Fields\ToggleField', ['name' => 'toggle_test', 'features' => ['title' => 'Toggle']]);
```

**Comment by rovillesarate** [comment]
![image](https://cloud.githubusercontent.com/assets/2109352/11420402/df05f992-9468-11e5-9f09-031e7995304d.png)
![image](https://cloud.githubusercontent.com/assets/2109352/11420410/e62e3a90-9468-11e5-8670-1b6ef30101f6.png)

This is located at addons/Field/Fields/Views/Metabox/_themosisToggleField.scout.php
![image](https://cloud.githubusercontent.com/assets/2109352/11420506/764818f8-9469-11e5-9287-339da195341a.png)

**Comment by jlambe** [comment]
An input of type `toggle` do not exists. That's your error. `Form::input` will generate an html input and use the first argument to define its type attribute. Plus you forgot to set it as a string. It is `'toggle'` not `toggle`. As this input do not exists, it will render a text input I suppose.

**Comment by rovillesarate** [comment]
Still not working. It was originally 
![image](https://cloud.githubusercontent.com/assets/2109352/11420903/32abb02a-946c-11e5-9b2e-62641bf1307e.png)

![image](https://cloud.githubusercontent.com/assets/2109352/11420893/22c6802c-946c-11e5-9ea5-51150de6f265.png)

Should the view be inside addons\field\fields\view\metabox\

or should it be on my actual views folder \ metabox?

**Comment by rovillesarate** [comment]
had to place it in both views folder and in the addons view folder / metabox but still getting the same error. Also tried placing it directly on the themosis core field view/metabox also not working.

I dont know what i am missing.

**Comment by jlambe** [comment]
What happens if you set this `Form::input('text', $field['name'], $field['value'], $field['atts'])`

**Comment by rovillesarate** [comment]
Still getting the same problem. I even tried just placing a text just to see if the error is going to change. Checked the form builder and saw text and checkbox have a function there. Maybe i need to extend it and insert a toggle function there?

**Comment by jlambe** [comment]
Can you post all your code on repo? And you still get the error telling that the FormBuilder class has no method 'toggle'?

You can remove the call to `$this->setType()` in the constructor method. This is only for media fields. Don't know which functions are you referencing to, the TextField has nothing except the fieldType method.

Stop looking after a toggle method as this input do not exists. Are you still receiving the error when you remove all the code from your field view?

**Comment by rovillesarate** [comment]
Still receiving formbuilder class has no method. Already tried removing everthing from the toggle view file but still getting the same error. Will upload the whole code in a repo in a while. Thanks julian for the fast support.

**Comment by jlambe** [comment]
That's weird. I can't see why it is trying to call the form builder class even when you have an empty view file. Will have to dig into code for this.

**Comment by rovillesarate** [comment]
Hi! Julien. I was able to make it work but it will only allow the view to be on the themosis plugin fields/view/metabox directory only. It can't seem to read on the addons or theme view directory.

Do i need to add some sort of code within the ToggleField to allow to search from the addons field view directory?

**Comment by jlambe** [comment]
Are you working on the theme? or building a custom plugin?

**Comment by rovillesarate** [comment]
from the theme

**Comment by jlambe** [comment]
Then only put your view inside the theme `views` directory. Create a custom name for your view file without a `_themosis` prefix as this is reserved to core view files. Make sure the name do not conflict with another view, best way to avoid this is by "namespacing" your views by creating a `fields` directory inside the `views` folder. Then call inside your class metabox method this: `$this->view->make('fields.customfield', ['field' => $this])->render();`

**Comment by rovillesarate** [comment]
It worked. Thanks Julien. It actually make sense using the theme view directory instead of using a separate view folder from the addons directory.
