### ISSUE TITLE
How do you make routes for non-wordpress created pages?

### ISSUE THREAD

**Issue by otherjohn** [themosis/framework#250]
Hi, I would like to create a single page app on a page ("/account/") that is handled from the controllers. I don't want to create "account" page in wordpress, but when I create the route 
```Route::get('page', ['account', 'uses' => 'AccountController@index']); ```, I get a page cannot be found.

How can I properly set this up?
Also, this is on a multisite setup so that might just make it more complicated.

**Comment by jlambe** [comment]
Hi, in order to do this, you'll need to use the WordPress Rewrite API: 
- [https://codex.wordpress.org/Rewrite_API](https://codex.wordpress.org/Rewrite_API)

1.  Basically, you'll register a custom query var using the [add_rewrite_tag()](https://codex.wordpress.org/Rewrite_API/add_rewrite_tag) function.
2.  Then you'll define rule that will compare the URI of the current request against your custom query var. For this, use the [add_rewrite_rule()](https://codex.wordpress.org/Rewrite_API/add_rewrite_rule) function. For example, WordPress will see the current URI as `/account/` and thanks to your rewrite rule, knows that it matches your custom query var value => OK, got a custom route.

Now, in order to use this inside your `routes.php` file, you'll need to write a route condition (a function) and register it with a framework filter `themosisRouteConditions`. The condition is nothing hard, simply check the query var and its value, then only return `true` or `false`.

Register your route condition:
```php
add_filter('themosisRouteConditions', function($conds)
{
    $conds['account'] = 'myRouteConditionFunctionName';
    return $conds;
});
```

Then inside your `routes.php` file:
```php
Route::get('account', function()
{
    return 'The account page';
});
```

Some people already asked for an helper class that will manage all this work for you but it's not yet developed. If you need an example of use for the Rewrite API, check our [themosis/todo](https://github.com/themosis/todo/blob/master/htdocs/content/themes/tasks/app/admin/tasks.php) repository code.

In theory it should work for multisite but don't hesitate to post your code and/or questions in this issue and I'll help you find out the solution.

**Comment by otherjohn** [comment]
Great, I will give it a try.

**Comment by jlambe** [comment]
For information, the current master branch of the `themosis/framework` package contains a full Illuminate/Routing implementation. You can try it now by cloning the `themosis/themosis` dev branch. It's early development and has some issues but of course I hope those will be fixed for release.
