### ISSUE TITLE
How to route for multisite?

### ISSUE THREAD

**Issue by otherjohn** [themosis/framework#251]
Can you route for multisite, meaning can I test for a certain site and perform routes based on what site it is, or pass the site_id to the controller?

**Comment by jlambe** [comment]
The framework do not provide a route for this by default. Normally when you hit the `routes.php` file, you're already in a specific site.

But if you're looking to use the same theme on multiple sites and perhaps based on the `site_id`, change the home page view or something else... I suggest to simply fetch the site ID inside a "regular" route and return a different view based on that.

In the code below, we return a different view for the home request for the site with an ID of 3:

```php
Route::get('home', function()
{
    $siteID = get_current_blog_id();
    if ($siteID = 3) return View::make('pages.special');

    return View::make('pages.regular');
});
```

Perhaps try to give me some details why you'll want to do this because perhaps it's best to use a View composer or View share to pass data to the views based on site ID.

**Comment by otherjohn** [comment]
Thanks. I will give this  a go
