### ISSUE TITLE
Question about your documentation

### ISSUE THREAD

**Issue by heikobihlmaier** [themosis/framework#257]
Hello,

I'm very new with your framework so I don't understand your documentation completly.

In which file I need place this for custom admin pages: http://framework.themosis.com/docs/page/
Also: How can I generate database models ?

Greetings

**Comment by jlambe** [comment]
In order to customize the WordPress administration, simply add a new file inside the `resources/admin` folder and add your code.

Regarding models, you'll store them inside the `resources/models` folder. There is no cli to auto-create a model class and there is no ORM to map your class to an existing database table. Currently this is very basic, you have to create a class manually and define your own methods in ordre to handle the data from and to the database. You can use core WordPress class like `WP_Query`, `WP_User_Query`, ... to handle data inside your model.

All you model class should be autoloaded by default using PSR-4. You can define a custom namespace thanks to the `resources/config/loading.config.php` file.

Regards,

**Comment by heikobihlmaier** [comment]
Hello @jlambe 

okay thanks.

And how can I make a complete own admin section with database, tables and so on ?

**Comment by jlambe** [comment]
WordPress has no migration tool. It uses pure SQL syntax to create tables and their schema.

However, using the WordPress plugin API, you can tell WordPress to create database tables when your plugin is activated (migration up) and remove/clean your tables when deactivated or deleted (migration down).

Take a look at this core documentation regarding the WordPress WPDB class:
- https://codex.wordpress.org/Class_Reference/wpdb

On future release, you'll be able to do this with the framework in more efficient and structured way but it's not yet available.
