### ISSUE TITLE
composer packages ?

### ISSUE THREAD

**Issue by DeeJaVu** [themosis/framework#264]
Hello, how can i use composer packages for example i installed the [Carbon package](http://carbon.nesbot.com/) in public_html outside htdocs

but when i use ```{{ Carbon::toFormattedDateString($post->post_date) }}```
i get class Carbon not found, pls help

**Comment by DeeJaVu** [comment]
i gave up and deleted everything, themosis is not for me

**Comment by jlambe** [comment]
Hi, sorry to hear you have troubles using the framework.

Regarding your issue, it is odd that you have installed the `Carbon package` in a folder called `public_html`. In order to use packages, simply add them into your `composer.json` file and run the cli command `composer update`.

Then anywhere in your code, you can call the Carbon classes like in your code above.

For what I can read from your post, your issue is a Composer issue, not a framework one. Perhaps it's best to learn more about [Composer](https://getcomposer.org/) before digging into Themosis.

Don't hesitate to try again! I'm here to help you if you have any questions!
Regards,

**Comment by DeeJaVu** [comment]
hello what i mean is i installed the composer package from my root folder where the composer.json and vendor folder is so i did "composer require nesbot/carbon" but when i use Carbon it says that the class Carbon is not found, other composer package works everywhere for example this https://github.com/digitalnature/php-ref

**Comment by jlambe** [comment]
That's weird indeed. But the class is namespaced. If you simply call `{{ Carbon::toFormattedDateString($post->post_date) }}` inside your view, it's normal that the class is not found. Default classname is `Carbon\Carbon::toFormattedDateString()`. In order to simply call `Carbon`, add a `use` statement at the top of your view file or simply define a class alias into your theme `application.config.php` file at the end, perhaps that's your issue.

**Comment by DeeJaVu** [comment]
ok i will try this again hope it works this time :)

**Comment by DeeJaVu** [comment]
hi Carbon\Carbon::toFormattedDateString() gives 
`"Non-static method Carbon\Carbon::toFormattedDateString() should not be called statically, assuming $this from incompatible context"`

and when i create an alias i still get class not found, this is my alias

```
'aliases' => [
		'Carbon' => 'Carbon\Carbon',
	],
```

not sure if its correct

**Comment by DeeJaVu** [comment]
waste of time, bye

**Comment by jlambe** [comment]
Can you post the code where you call your Carbon class?
Regarding aliases, yeah this is my fault, there is an issue regarding custom aliases. The fix is currently in the master branch and will be soon released.
Nonetheless, I've tested the Carbon package and it works as expected. The error tells you that the method `toFormattedDateString()` is not a static method. Looking at the docs it's seems to be an instance method.

```php
$dt = Carbon\Carbon::create(1975, 12, 25, 14, 15, 16);
echo $dt->toFormattedDateString(); 
```
