### ISSUE TITLE
How to use themosis directly from the plugins folder of wordpress

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#285]
Hi! How do you use themosis plugin directly from wordpress plugin without using composer create-project. I am currently using a third party theme but for some reason the theme can be activated but getting problems with some of its code having conflict.

I would like to try to just install themosis framework directly from the plugins folder just to check if this will fix the problem with the current theme that i am using.

When i try to install themosis from the plugin folder. it says autoload is missing.

**Comment by jlambe** [comment]
You can download the zip file from the themosis/framework repository and place it under your plugins directory. Once copied, you still need to initialize it by doing a `composer install` call in the cli because the plugin needs some dependencies that are not bundled with it.

Then work like usual inside your theme.
