### ISSUE TITLE
Cannot use InfiniteWP together with themosis

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#288]
Hi Guys,

For already a long time we are running into an issue where we can not add a wordpress site which is build using themosis in infinitewp. 

We successfully added the InfiniteWP client plugin. It shows us the credentials to put into the the infinite wp admin panel to register the site but we only get the error message

Yikes! It appears IWP plugin has not been installed in this site. Click here to Install it.
OR
If you have already installed IWP Plugin, deactivate and activate it now.

Are there people who can help us fixing this or have InfiniteWP working with their themosis sites?

Thanks

**Comment by jlambe** [comment]
Hi, I shared your issue on Twitter in order to find someone to help you into this. I've never used infinitewp to manage websites so I can't really help you.
But is InfiniteWP looking after the `wp-config.php` file during its process? It is weird you get an admin notice when you install their plugin though. Perhaps digging into their source code might help debugging this.

**Comment by ryami333** [comment]
@dstollie did you ever manage to resolve this? Having the same problem.

**Comment by dstollie** [comment]
No unfornutately not..

**Comment by jlambe** [comment]
Do you have any error logged for this besides their admin notice?
