### ISSUE TITLE
Route Parameters

### ISSUE THREAD

**Issue by simplethemes** [themosis/framework#291]
Hi, I'm just getting started with Themosis, so please forgive my amateur-ish question.

I've included the Eloquent package for some external models, but the WP response is always 404.

For this particular part of my application, my model is not a page nor post, but rather some externally synced resources. How might I go about fetching these based on the following URL structure?

````
// routes.php
Route::get('properties', 'PropertiesController@index');
Route::get('properties/{id}', 'PropertiesController@show');
Route::get('properties/nearby', 'PropertiesController@getnearby');

// resources/admin/routing.php
add_filter('themosisRouteConditions', function()
{
    $conds['properties'] = 'is_property';
    $conds['properties/{id}'] = 'is_single_property';
    return $conds;
});
````

**Comment by jlambe** [comment]
WordPress is always handling the routing behind the scenes. So based on your routes, you want it to find a `WP_Post` with a slug of `properties` which of course do not exists because you haven't setup any custom post type for these.

One way to make it understand those routes, is to use the WordPress [Rewrite API](https://codex.wordpress.org/Rewrite_API).

You'll use two functions here to set this up:
- [add_rewrite_tag()](https://codex.wordpress.org/Rewrite_API/add_rewrite_tag)
- [add_rewrite_rule()](https://codex.wordpress.org/Rewrite_API/add_rewrite_rule)

WordPress default URLs are query based: `domain.tld?p=25&post_type=something`
And rewrite rules allow WordPress to translate this for example: `domain.tld/something/25` into the default url just above.

So first, use the `add_rewrite_tag()` function to define query variables and tell WordPress to recognize them. Basically, creating the default url with query vars.
Second, use the `add_rewrite_rule()` function to define the pretty URL to look for and tell WordPress it corresponds to default query URL.

Finally for your Routes to be available into the framework, you'll create helper functions called (from your code), `is_property` and `is_single_property` where each methods will look at the URL, search if the query vars for your route exists and return true or false accordingly. Use the [get_query_var()](https://codex.wordpress.org/Function_Reference/get_query_var) function.

Example:
```php
// With a default URL = domain.tld?property=1 and pretty URL = domain.tld/properties/
function is_property()
{
     return get_query_var('property', false); // Second argument is default value if not found.
}
```

Then your condition above is available to the routes.
So this will work: `Route::get('properties', 'PropertiesController@index');`

Hope this helps.

**Comment by simplethemes** [comment]
Thank you for such a detailed response.

My Laravel application has some pretty deep functionality (custom service providers, filesystem, and job queues) so I'm thinking I'll leave it in place. In the end, I just want to be able to pull my models into WP views and still use the CMS for standard functionality. Would you say that Themosis is a good candidate for something of this nature?

**Comment by jlambe** [comment]
If you want to only pull data and display it, **sure WordPress is a great candidate** for this. Themosis is WordPress development with some sugar on top.

For easy integration, I suggest you to put API endpoints to your Laravel application and from WordPress, simply call the `wp_remote_get()` function to fetch your Laravel application data and display it into WordPress.

Then if your data isn't often changing, you can store it into WordPress and fetch daily or weekly in order to update it.

**Comment by simplethemes** [comment]
Thank you again. I hadn't even thought about `wp_remote_get()`. Nevertheless, I need to resolve the URL and display the appropriate template.

In my routes.php I have:
`Route::get('properties', 'PropertiesController@index');`

And in resources/admin/application.php I have the following functions:

This, I believe creates a pretty URL for /properties:
````
function h2theme_rewrite_add_rewrites() {
    add_rewrite_rule(
        '^properties/?$',
        'index.php?properties=true',
        'top'
    );
}
add_action( 'init', 'h2theme_rewrite_add_rewrites' );
````

And this adds it to the public query vars:
````
function h2theme_rewrite_add_var( $vars )
{
    $vars[] = 'properties';
    return $vars;
}
add_filter( 'query_vars', 'h2theme_rewrite_add_var' );
````
And I have added the Themosis route logic:
````
// Add the conditional function to the Route class.
function is_property()
{
    return get_query_var('properties', false);
}

add_filter('themosisRouteConditions', function($conds)
{
    $conds['properties'] = 'is_property';
    return $conds; // Always return an associative array.
});
````
This has no effect, however. If I add `echo get_query_var('properties')` in my view, it does however return true.

In the end, I just want to return a view from the controller for /properties and /properties/{id}.

Am I `_doing_it_wrong`? ;)

**Comment by jlambe** [comment]
Use the `add_rewrite_tag()` function to add your query var in place of the filter. Then flush the rewrite rules by visiting the permalink page in admin and click save. (You can also flush rewrite rules programmatically but it's best to flush on plugin activation).

Rewrite rules are saved in the database permanently so always flush them in order to update it.

Then, in theory, everything should be working ;)
