### ISSUE TITLE
Idea: Support for url based routes instead limiting to wordpress' route conditions

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#292]
@jlambe 

I was walking through the issues and after if read the last issue I was thinking.. why do custom routes have to be so much work to implement. And wouldn't is be way more awesome if we could just do 

```php
Route::get('/article/(.*?)/create', 'ArticleController@create'); 
```

Where the first match in this case will be added to the route method:

```php
class ArticleController {

public function create($routeProperty) {
 //tood implement
}

}
```
We could extend the router to not only check if there if the route condition is available but also check make it able to do a regex check and check if the current url the user is at matches the a given regex condition in the route. 

I think this should be fairly simply implemented but before I even trying to I want to discuss it with you.

So far so good,

Dennis

**Comment by jlambe** [comment]
I'm not against the idea and habitually, that's how it works!

WordPress has a different way of doing routing because it "automatically" associate data to the URI. Where if we define "classic" routing, by visiting an `/articles/create` URI, no data from WordPress should be retrieved because it's not supposed to be. So it's "easy" to add classic routing to WordPress but I also want to be sure that on every response, we do not run over too much processes because WordPress retrieve some data that have nothing to do with the request. (like retrieving the latest 10 posts or more...)

I'm open to suggestions anyway and if you have time to implement something, don't hesitate to make a pull request or a fork of the framework and we'll test and discuss it.

**Comment by jlambe** [comment]
PR merged and currently functional on master branch. Need feedback.
