### ISSUE TITLE
Problem with create routes for custom page

### ISSUE THREAD

**Issue by haupv** [themosis/framework#297]
Hi there,
I got a problems with create a custom slug to call a custom page.
For ex: i have two pages in views folder: ** product.php ** and  **shop.php**

when user type: http://localhost/**product**  => will call a product.php page
when user type: http://localhost/**shop**  => will call a shop.php page

I have made routes like this:

	add_filter('themosisRouteConditions', function($conds)
	{
		
		$conds['product'] = 'is_product';
		$conds['shop'] = 'is_shop';
		return $conds;
	});

	Route::get('product', function(){
		return View::make('product');
	});

	Route::get('shop', function(){
		return View::make('shop');
	});

but when call http://localhost/**product** or http://localhost/**shop** 
it only return a product page. I can't access to shop page

did i get a mistake ?!
thanks so much !

**Comment by jlambe** [comment]
In fact, in WordPress, you have to somehow think in the contrary :smiley: 
On a habitual "framework" flow, you start with a route that checks for an `uri` and you assign a view (or controller first) to display content for this specific uri:
- mydomain.com/**shop**: use the `shop.scout.php` view file
- mydomain.com/**product**: use the `product.scout.php` file

The "issue" here is that WordPress won't recognize those URIs by default. In order to make it understand this, you need to create that content first from the `wp-admin`. So for example, you create a page from `wp-admin`, you give it a title of `Shop`, you publish it and WordPress will make this exact page content available to this url: `mydomain.com/**shop/**`.

Now in your code, I suppose you have installed the `WooCommerce` plugin? Then your code should work as expected if there are two pages published into your WordPress installation:
- Shop
- Product

Which normally should not exist based on Woocommerce as `products` are a custom post type which should then be used with a singular route in order to display the content of one product:

```php
Route::get('singular', ['product', function()
{
    return View::make('shop.product');
}]);
```

So, if you don't have WooCommerce installed, simply create the 2 pages in `wp-admin`:
- Shop
- Product

then simply use these routes to show their content:

```php
Route::get('page', ['shop', function()
{
    return 'Shop page content';
}]);

Route::get('page', ['product', function()
{
    return 'One product content';
}]);
```

and simply get rid of the rest of your code.
Hope this clarifies your issue.

**Comment by jlambe** [comment]
The next release 1.3.0 (and current master branch) has the Illuminate Routing package fully integrated. Will be much easier to create custom routes without being tight to WordPress data.
