### ISSUE TITLE
Confused over purpose of the framework.

### ISSUE THREAD

**Issue by dryajov** [themosis/framework#309]
Hi, I've been looking at both http://getherbert.com/ and themosis, and were it is clear that herbert is a framework specifically for developing plugins, I can't figure out what themosis's purpose is, is it a theme or a plugin development framework, or both? I'm in the process of choosing and would appreciate if someone could list the differences.

Thanks!

**Comment by bactisme** [comment]
What are you building : a wordpress plugin or a website?

Other will complete my response, but I see themosis as a way to do modern development (Separation of concerns, MVC, powerful routing, staging environnement) on top of the (aging) wordpress framework.

I have several websites. I built them with themosis, but still do plugins for all tasks shared between two instances.

**Comment by jlambe** [comment]
The current version of Themosis allows you to better manage the development of a WordPress website. It provides shortcuts and an object oriented development for WordPress.

Getherbert is only aimed at plugin development. My main issue with it is that you need to load a full framework for each plugin you develop.

The next release of Themosis is going to help you build a structured WordPress website as well as give you the ability to build plugins. Themosis provides a `mu-plugin` that contains all core classes and then you use those APIs into your plugins and theme in order to build your WordPress website or application.

Themosis is going to work as a full-featured "stack" for WordPress development where GetHerbert is only for plugin development.

Hope this helps, if you have other questions, don't hesitate to ask!

**Comment by dryajov** [comment]
Thanks! Thats the impression I got from looking at both frameworks, but wasn't sure. 

Another question I have is regarding integration of themosis with existing themes? With a plugin, I can drop functionality into an existing theme, without having to do any major changes, is that possible with themosis?

**Comment by jlambe** [comment]
Using Themosis is still WordPress development. So you can develop any plugins using WordPress functions and APIs and it won't interfere with your theme. If you have an existing theme, Themosis is not going to break it. Themosis is a group of classes to help you build custom features into your WordPress project. You can activate any kind of themes and it will just work.

In general, it is always better to develop features with plugins and only use the theme for front-end styling. Hope this helps.

**Comment by dryajov** [comment]
Thanks for the quick replies!
