### ISSUE TITLE
What's the best place / method to add custom fields to user

### ISSUE THREAD

**Issue by Cezarion** [themosis/framework#317]
Hi ! 

I need to add extra fields per role and I don't if where to write the corresponding code : 
in a UserModel ? 
in a add_action show_user_profile ? 

Thank's a lot for your help.

**Comment by jlambe** [comment]
Currently you can add custom fields to users profiles but the fields are displayed for all users whatever roles they might have.
Defining custom user fields per role is a feature proposed for a later released.

In order to add custom users fields, I suggest you to add a new file in your `admin` folder and write your code in there. Check the users documentation for custom fields: http://framework.themosis.com/docs/user/

**Comment by Cezarion** [comment]
Thank's a lot, you're really quick to respond. 
I read the post about the feature. It will be great. 
I started to write code in this folder .. I was on the right track. 

Have a nice evening

**Comment by jlambe** [comment]
Thanks! All the best for you as well.
