### ISSUE TITLE
Multi-Site functionality

### ISSUE THREAD

**Issue by iamkevingreen** [themosis/framework#32]
I've tried to get this working with both subdomains and the file structure method. Whenever I do it breaks Themosis in varying ways and I think it has something to do with how multisite tries to control the rewrite rules while themosis is also trying to control the routes.

Have you had experience with a working multisite instance? I've added the multisite to my shared configuration but once again have to flatten the database because I can't seem to get the admin state to work and it also seems to break the routing. It also forced a /blog/ prepend to the custom routes which isn't something that I desired. 

Any documentation on how this should be set up would be much appreciated, I am going to explore potentially not using multisite but it would make it much easier to keep a lot of this content separate.

**Comment by mediastuttgart** [comment]
Hey,

Today i was testing the multisite functionality with themosis and it seems that there are some issues with the rewriting as mentioned above. Some backend links include the `cms/` fragment in the URL some do not.

It seems that the initial site (the site created before activating the wordpress network) is using the correct URL scheme including the `cms/` fragment while all further sites created with the wordpress network feature do not.

After playing around with some configurations, i was able to access admin menus and settings of the other sites (but only without the `cms/` fragment). On the other hand the frontend of the initial site was only accessible through `example.com/cms/` while the frontend of the other sites gave me a 404.

Unfortunately i was not able to figure out what exactly is causing these issues.

Following the suggestion of trying a classic wordpress installation and simply adding the themosis framework plugin and theme i was able to get the multisite feature running. Everything seems to work as expected.

However when using this approach the `index.php` file inside the theme directory is accessible from the browser. So i did a `silence is gold` to the themes `index.php` and moved the `themosis_start_app()` to `wp-blog-header.php`.

**Comment by mediastuttgart** [comment]
Unfortunately my solution with the `index.php` is crap, since when you are using different themes for your network sites you will receive an error because the function `themosis_start_app()` is unknown in other themes than themosis.

Also the `functions.php` is accessible from the browser. @jlambe do you have any advice for that issue?

**Comment by jlambe** [comment]
Hi,
currently I have no advice on how to fix these issues.
1. The issue with `/cms` URI on some requests, I'm wondering if it's not a core WordPress issue when defining/moving WordPress in its own directory.
2. I only tested once with one theme. Seems to work (except the `/cms` issue), I haven't encounter an issue where the `index.php` file is visible to the browser.

I'm reopening this thread so I can come back to it later and check what I can do for multisite installations. For the moment, unfortunately, the framework is best for single installation.

**Comment by mediastuttgart** [comment]
**Access Issues**

Since i am new to wordpress i am not sure about this behavior but if you enter this URL into your browser 
(`cms/content/themes/themosis-theme/functions.php`) you will see a fatal error regarding *Call to undefined function get_template_directory_uri()*. I am not sure but i assume this file should not be directly accessible.

But as this topic is about multisite feature i will open another issue for that one if this is okay for you?

**Multisite Feature**

Finally i get the *multisite feature with subdomains* to work with the themosis framework. There are a few things you need to adjust before everything works as expected. Now lets start from the beginning so everyone else can follow up.

1) Add `define('WP_ALLOW_MULTISITE', true)` to your environment (for example `config/environments/local.php`).

2) Login to the backend by visiting *http://example.com/cms/login* and start the multisite installation.

3) Add the following to your `.htaccess` file.

````apache
RewriteEngine On
RewriteBase /

# BEGIN WordPress
RewriteRule ^index\.php$ - [L]
RewriteRule ^wp-admin$ wp-admin/ [R=301,L]
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^cms/(.*) $1 [L]
RewriteRule ^(wp-(content|admin|includes).*) cms/$1 [L]
RewriteRule ^(.*\.php)$ cms/$1 [L]
RewriteRule . index.php [L]
# END WordPress
````

4) Add the following to your environment file (for example `config/environments/local.php`) where `DOMAIN_CURRENT_SITE` should match your site URL without any extra fragment. Also leave `PATH_CURRENT_SITE` without the `cms/` fragment since the `.htaccess` file is already taking care of that.

````php
define('MULTISITE', true);
define('SUBDOMAIN_INSTALL', true);
define('DOMAIN_CURRENT_SITE', 'example.com');
define('PATH_CURRENT_SITE', '/');
define('SITE_ID_CURRENT_SITE', 1);
define('BLOG_ID_CURRENT_SITE', 1);
````

5) Add the following to your environment file (for example `config/environments/local.php`) as this will prevent a possible redirect loop when trying to login to other sites created in the network.

````php
define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');
````

6) Check your database tables `wp_options` and `wp_sitemeta` for any values regarding `home` and `siteurl` and remove the `cms/` fragment. This step is important since the `.htaccess` file is already taking care of that.

7) Now login to the backend by visiting *http://example.com/login* (**without the `cms/` fragment**).

**Comment by cdarken** [comment]
@mediastuttgart @jlambe Any hints how do you proceed with development after configuration? Do you duplicate your theme? Or do you use a common theme for the entire network? How do you route depending on the accessed site?

**Comment by jlambe** [comment]
Hi,

not tested yet but I suppose you can do whatever you like:
1. Activate your theme for the entire network
2. Activate your theme per site

In theory, development shouldn't change at all compare to single installation. The route system is using core WordPress conditional functions to find out which "view" to use. So for whatever "sub-site", a `page` route is listening on page request for the current site only.

**Comment by jlambe** [comment]
@mediastuttgart I'm currently testing a sub-domain multi-site installation and the only database change I had to do is in `wp_options` and remove the `cms` fragment in the `home` value.

The `siteurl` is the address of the WordPress files so it has to stick this way. Only change the `home` value.

**Note:** Even on a single installation the `home` value is specified with the `cms` URI. It seems that WordPress is able to ignore this parameter in some way for single installation but not on multisite. Perhaps a core update will fix this issue. Will probably report it.

**Comment by cdarken** [comment]
Having problems with this on the production install. Locally, using apache and the same domain name set in /etc/hosts, it's working, but on production, if I try to access /cms/wp-admin/ it redirects me to the homepage. Any hints how can I debug this? Is it wordpress, is it apache or the rewrite rules? I don't have any ideas.

**Comment by jlambe** [comment]
By default, the framework do not allow non-logged users to access the `wp-admin` area. You need to go to this URI: `/cms/wp-login.php`

**Comment by cdarken** [comment]
Sorry, I wasn't very clear, that happens after I authenticate as admin.

**Comment by jlambe** [comment]
Can you check the installation steps from the framework documentation and let me know how it goes: [http://framework.themosis.com/docs/multisite/](http://framework.themosis.com/docs/multisite/)

It might also be a permalink issue, check the .htaccess file on your production server and compare it with the local one.

De-activate any plugins added perhaps if you have some.

**Comment by cdarken** [comment]
Wow, thanks for adding new info on the site. That will be helpful in the future. My problem was different, as I found out just now. It looks like the rights of the admin user were downgraded somehow, that's why I was redirected from the admin section. I found it just in time before losing my mind.

**Comment by jlambe** [comment]
Cool, glad you resolved your issue. Will there be an URL to your public project so I can see what you've created with WordPress and the framework?

I would like to open a showcase page on the framework website later on.

**Comment by cdarken** [comment]
I will let you know when the site will be live.

**Comment by jlambe** [comment]
There is finally a trac issue posted on WordPress core for this: https://core.trac.wordpress.org/ticket/33909
