### ISSUE TITLE
Plugin dev using thermosis with a roots/bedrock install

### ISSUE THREAD

**Issue by beatelite** [themosis/framework#324]
Hi, I'm already using the roots/bedrock stack. However, I am looking for an MVC framework for plugin development. I ran across herbert but I worry with the dearth of examples, docs and community that they don't plan to maintain the framework for long. You're doing all the right things here and wish I heard about you before I chose bedrock 2 years ago. 

Questions:

1. Could I use thermosis to develop some plugins for my app while still using the bedrock stack or do I need to convert my wp stack to yours? 
3. If so, how hard is this?
4. If not, is there anything I need to look out for when using your framework just for plugin development? 

Let me know and thanks in advance. Looking forward to diving in.

**Comment by jlambe** [comment]
Hi,
1. It's possible to use the framework by keeping your stack but it demands a lot of manual code changes. I will suggest you to start from scratch with a new Themosis stack and move your theme and plugins over. **Note:** The current released version (1.2.3) is not optimized to develop plugins. If you're feeling adventurous, I'll suggest you to use the `themosis/themosis` repository `dev-branch` in order to do so. This dev version is stable enough for production but there is no documentation against new APIs and how to structure your plugin code with future version 1.3.0. **Tip**: The `functions.php` file from the `themosis/theme` in its dev-branch can give you some directions on how to bootstrap a plugin. But you can ask questions over here or in the Gitter chat room: https://gitter.im/themosis/framework?utm_source=share-link&utm_medium=link&utm_campaign=share-link
2. Not that hard I suppose as Bedrock is just giving a bootstrap structure. Mainly it will be to start a new project and simply move your plugins and theme over the Themosis instance.
3. As explained, for plugins development, I'll suggest you to use the current `dev` branch of the `themosis/themosis` repository. But it lacks documentation for the moment. There will be a full documentation regarding plugin development but it's not yet ready.

If you have more questions, don't hesitate to ask!
Regards,

**Comment by beatelite** [comment]
Thanks mill for the detailed reply! It sounds like I'd have to move my whole stack which may be a bit more work than I want to do for this at the mo.

However, the dev branch sounds interesting. When you anticipate a release with docs?

Thanks again!

**Comment by jlambe** [comment]
No release date announced yet 😄  But it's on the pipeline
