### ISSUE TITLE
Theme customizer

### ISSUE THREAD

**Issue by LeRondPoint** [themosis/framework#331]
I was looking into adding options to my theme this morning.  I thought I could use the Page API to do so.  Turns out it is not the case, even though the documentation does mention options pages, they are always «dashboard level» admin pages.  To top it off, the live preview dorsn't work in the customizer.

So I see a couple of issues here:
1) No way of dealing with theme customizer options
2) Not working customizer live preview (No route defined error)
3) Misleading documentation

This is a big part of theme ease of use from a user's perspective so I think it deserves some attention!

**Comment by LeRondPoint** [comment]
Just saw issue #37 for the preview!!!

**Comment by jlambe** [comment]
The documentatin mention page settings for building options page using WordPress Settings API:
- http://framework.themosis.com/docs/page/

See WordPress Settings API down the page with the use of `addSections()` and `addSettings()` methods.

The framework do not provide API to work with the customizer, this will be for release 1.4.0. You have to stick with core WordPress functions to do so. The customizer is using `post` method so i you need at least to define `Route::match(['get', 'post'], ...)` or `Route::any()` to work with the customizer or separates routes for the `post` and `get` requests.

The Page API allows you to build custom admin page without the use of the settings API. In order to customize an admin page, simply pass it a custom view as 4th parameter. It's best to pass data to custom admin  page view with the help of a composer view.

Hope this clarifies a bit.

**Comment by LeRondPoint** [comment]
It does and I had it figured out.  However, I think the documentation shot be explict about the theme options not being in the customizer, because that is what most themes do out there.

I assumed that "options", in the context of a theme framework, would be in the customizer by default.  Actually, I would even say that "admin pages" never crossed my mind until I saw it appear!

So anyways, cool for now,  Thanks!

**Comment by LeRondPoint** [comment]
As I go along, I'll mention stuff that would be good additions to 1.4 regarding customizer.

- Add 'customizer' to the possibilities for Asset::to function

**Comment by jlambe** [comment]
Yup customizer assets will come on later version.
Also note the the `Page` API in the framework is related to admin pages. It doesn't mean Theme Options page in both WordPress and the framework terms. It's because those pages were used to provide theme settings by many developers that there is perhaps this "confusion" but a `Page` instance has nothing to do with theme.
Just for clarification ;)
