### ISSUE TITLE
Support for wp-api for rest endpoints

### ISSUE THREAD

**Issue by dstollie** [themosis/framework#353]
Since WordPress is also adopting the wp-api in it's core I think we really should implement this in Themosis. What do you think? 

--
Meanwhile im was testing using the speed difference between an laravel route route as an endpoint and the wp rest api route but I do not see any difference in speed

**Comment by jlambe** [comment]
Well at the moment I don't want to focus on it as it is subject to changes. The default API for the wp-api is still easy to grasp.

And as we have the full Illuminate Router, it's also easy to define custom endpoints.

Once the release 1.3.0 is out (which is due very soon), my focus will be on the fields API and refactor it completely to indeed be completely integrated with new core API that leverage `register_meta` in order to define value type and work seamlessly with meta data, customizr and wp-api.
