### ISSUE TITLE
Class 'Theme\Models\WP_Query' not found

### ISSUE THREAD

**Issue by bumbella** [themosis/framework#388]
Hi, i like your Themosis framework. Very easy and so clean. I have a problem. In basic model I get Class 'Theme\Models\WP_Query' not found error. I can't solve this problem. Please help me.

My model in models folder:
namespace Theme\Models;

class Query_Builder
{
    public function all()
    {
        $query = new WP_Query([
            'post_type' => 'post',
            'posts_per_page' => -1,
            'post_status' => 'publish'
        ]);

        return $query->get_posts();
    }
}

**Comment by jlambe** [comment]
Hi @bumbella, because of the namespace, PHP can't find the WP_Query class as it is defined without a namespace in WordPress.

Calling the class like so:
```php
namespace Theme\Models;

new WP_Query();
```
will tell PHP to look after a `Theme\Models\WP_Query` class which do not exists.

In order to resolve your issue, you can import the class like so:

```php
namespace Theme\Models;

use \WP_Query;

class Query_Builder
{
    public function all()
    {
        $query = new WP_Query([
            'post_type' => 'post',
            'posts_per_page' => -1,
            'post_status' => 'publish'
        ]);

        return $query->get_posts();
    }
}
```

or prepend its name with a `\` when creating a new instance like so: `new \WP_Query()`

Hope this helps.

**Comment by marcwieland95** [comment]
You have to add `use WP_Query` below your namespace declaration, because WP_Query doesn't life inside this namespace.

**Comment by bumbella** [comment]
:D thanx for your quick feedback. This is good job. My code is run. Respect jlambe :)
