### ISSUE TITLE
login not found

### ISSUE THREAD

**Issue by maitrepylos** [themosis/framework#397]
Hello Julien, I just installed Themosis and I get a 404 error on the login page. What are the avenues to be explored to solve this road problem?
Thank you.

https://dev-toto.aei.be/login

**Comment by jlambe** [comment]
Hello Gégé :),

I think the issue might be the WordPress configuration over https. WordPress do not handle https automatically, at least for the admin part as you need to explicitly tell it to use https in order to work properly.

In your project `.env.xxx` file, you normally have a WP_HOME and WP_SITEURL set with https. Then for your staging/production environment config file (config/environments/production.php or any other files you might have defined there), add the following constant:

```php
define('FORCE_SSL_ADMIN' , true);
```

You can also add this configuration into the `config/shared.php` file if you use https on all environments.

Now what's also weird is that it cannot find the `https://dev-toto.aei.be/cms/wp-login.php` file, which is where you'll be redirected if you used the `/login` URI. Is that file there?

**Comment by maitrepylos** [comment]
My environment is composed like this:
Aei.be points to my web server, on which I create an apache proxy that redirects to my dev server.
`<VirtualHost *:80>

   ServerName dev-toto.aei.be
   ServerAdmin gerard.ernaelsten@aei.be

   ErrorLog  /var/log/apache2/proxy/dev-toto-error.log
   CustomLog /var/log/apache2/proxy/dec-toto-access.log combined

   RewriteEngine On
   RewriteCond %{HTTPS} off
   RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

</VirtualHost>

<VirtualHost *:443>

   ServerName dev-toto.aei.be
   ServerAdmin gerard.ernaelsten@aei.be

   ProxyPass / http://xxx.xxx.xxx.xxx/toto/htdocs/
   ProxyPassReverse / http://xxx.xxx.xxx.xxx/toto/htdocs/


   ErrorLog  /var/log/apache2/proxy/dev-toto-error.log
   CustomLog /var/log/apache2/proxy/dec-toto-access.log combined

   SSLEngine On
   SSLCertificateFile /etc/apache2/ssl/wildcard.aei.be.crt
   SSLCertificatekeyFile /etc/apache2/ssl/wildcard.aei.be.key
   Include /etc/letsencrypt/options-ssl-apache.conf
   SSLCaCertificateFile /etc/apache2/ssl/gandi.crt

</VirtualHost>
`


My dev server is a basic php apache (rewrite ok)

I put this in the .env

`WP_HOME = "https://dev-toto.aei.be"
WP_SITEURL = "https://dev-toto.aie.be/cms"
`

If I try locally: https://dev-toto.aei.be/cms/wp-login.php this redirects to https://xxx.xxx.xxx.xxx/toto/htdocs/cms/wp-login.php

wp-login is true

Thank you for your help.

**Comment by jlambe** [comment]
Note that the default theme blocks access to the `/wp-admin` and `/admin` URI. You can only use the `/login` URI or directly access the `/cms/wp-login.php` file to log in.

**Comment by maitrepylos** [comment]
The documentation is clear on it, but it still does not work, I must have a redirect problem.

**Comment by JosephNC** [comment]
I had the same problem,
This worked for me.
I just tried the permalink side of WordPress, changed to Post Name type and saved.
