### ISSUE TITLE
Add middleware route

### ISSUE THREAD

**Issue by Givx** [themosis/framework#400]
Hi, 

if it's possible to add middleware route.

**Comment by jlambe** [comment]
In order to define middleware, you can register middleware from the `RoutingService` stored in the theme's `resources/providers` by using the route `middleware` method like so:

```php
Rouge::middleware('your.middleware.name', Com\Middleware\CustomClass::class);
```

The above method is registering a middleware class `Com\Middleware\CustomClass` that should be defined in your theme or plugin. There are no pre-defined directory for storing middlewares but we suggest you to place them inside the `resources/middlewares` folder and setup an autoloading config that points to that directory.

Here is an example of a middleware class structure:

```php
<?php
namespace Com\Middleware;

class CustomClass
{
    public function handle($request, \Closure $next)
    {
        // Write middleware logic here...
    }
}
```

and finally, you can use your middleware on any route like so:

```php
Route::get('home', function () {
    return "Hello World!";
})->middleware('your.middleware.name');

// or on a route group
Route::group([
    'prefix' => 'twitter',
    'middleware' => 'your.middleware.name'
], function () {
   // routes
});
```
Hope this helps.

**Comment by Givx** [comment]
Ok, thanks

but you are an error in your exemple : 
Route::aliasMiddleware('your.middleware.name', Com\Middleware\CustomClass::class);

**Comment by jlambe** [comment]
I'll need to take a look at this. On client projects, the above code is working as expected.

**Comment by jlambe** [comment]
Middleware full support on `develop` branch.
