### ISSUE TITLE
Metabox::make without static data

### ISSUE THREAD

**Issue by Amorfx** [themosis/framework#422]
Hello. I use themosis in **1.2 version** and i have a question about metabox in themosis.

I create a post type and so i add multiple meta to it. So i create Metabox with Metabox::make. But.. i want to use Field::checkbox with no static data (i take data in my db). So to not call my db in all page i use the wordpress action 'add_meta_boxes_my_posttype' but if i do that the metabox is not created ... 

So i think of a solution to fill the metabox inside the action but it doesn't work... Why can i create metabox inside a wordpress action (add_meta_boxes here) ?

Thanks.

**Comment by Amorfx** [comment]
I found a solution of my problem but if it's possible to you to think about it ?
`function metaBoxProductCategoriesSet(){
    $screen = get_current_screen();

    if($screen->post_type != POST_TYPE_PRODUCT){
        return;
    }

    global $productCategoryMetaBox;

    $productCategories = ProductModel::getProductCategories();
    $pcForMeta = array();
    foreach($productCategories as $tag){
        $pcForMeta[$tag->term_id] = $tag->name;
    }

    $productCategoryMetaBox->set(array(
        Field::checkbox(
            'productCategory',
            $pcForMeta
        )
    ));
}

add_action('load-post.php', 'metaBoxProductCategoriesSet');
add_action('load-post-new.php', 'metaBoxProductCategoriesSet');`

**Comment by jlambe** [comment]
@Amorfx Another possibility would have been to set a custom metabox view with a view composer and then from the composer callback, call your product model and add pass your custom field.

But indeed it is something we can look for better performances on the admin part. Your solution sounds ok by hooking into the `load` action hook of an edit page. But as this hook is sooner than the one used by the metabox, you could simply wrap a default `Metabox::make()` call into your load hook callback instead of relying on a `global` variable out of the scope.

**Comment by Amorfx** [comment]
Thanks for the reply and yes i can remove the global :)

Thank you !
