### ISSUE TITLE
Cannot access Themosis on Mac - DocumentRoot /Library/WebServer/themosis/

### ISSUE THREAD

**Issue by al-esok** [themosis/framework#433]
Hello,

There will be a project starting next week on themosis and I cannot figure out how to run it on my mac.

I installed another wordpress project in the same directory and it is working but not the themosis project.

The error message that I get is : 
Forbidden
You don't have permission to access /themosis/ on this server.

Do you know/pin-point my mistake here? 

Thanks,
Avinash

**Comment by noxify** [comment]
Hi @al-esok, 

I'm working also on an OSX system.

The main url for a themosis instance is something like `http://localhost/themosis/htdocs`.


P.S. i'm using https://www.mamp.info/ for my local environment, because it's easier to manage everything (e.g. creating new aliases like themosis.local) (some features are only available in the PRO version).

**Comment by ramon-villain** [comment]
Did you configure your .env file correctly? And also if you're not using any mamp/laravel valet, you should try accessing `yourlocal.dev/htdocs/`

**Comment by al-esok** [comment]
Hello,

Thanks for your answers.

I managed to make it work using the default apache2 on the mac. 

I had several issues with the installation and my vhost but now everything is working like a charm.

thanks again :)

**Comment by jlambe** [comment]
@al-esok Glad your issue is solved.
Thanks @noxify, @ramon-villain for the help.
