### ISSUE TITLE
How would you go about handling woocommerce cart and checkout on themosis

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#434]
Hi! Guys. How do you handle woocommerce cart and checkout processing on themosis?
Do i also have to create a route for the cart and checkout post?
Any guide or suggestions. Thanks!

**Comment by noxify** [comment]
Hi,

i think, you have to create your own routes.
There is an example in the documentation to extend the routes condition:
http://framework.themosis.com/docs/1.3/routing/#extending-wordpress-routes

**Comment by rovillesarate** [comment]
lets say i already created a custom routes for this but isn't woocommerce checkout processing is done automatically? how will i link the checkout processing on the custom route?

**Comment by jlambe** [comment]
@rovillesarate One thing to keep in mind is that woo commerce cart and checkout are regular WordPress `page` entities. You could also write a `Route::page()` and check the query parameter to know if you're on a cart or checkout page from your route callback or controller method.

Also since release 1.3.x, the only place to extend the route conditions is from within the RoutingProvider class right before the call to the theme `routes.php` file.

**Comment by jlambe** [comment]
Release 2.0 has better compatibility with WooCommerce. Plan to add a documentation on how to support WooCommerce using the new theme coming with next release.
