### ISSUE TITLE
How do you include and use the fpdf package

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#446]
Hi! How do i include the fpdf package with themosis?

I already composer require the fpdf package

how do i use it?

**Comment by jlambe** [comment]
Don't know your package but definitely like any package, set it up into the main composer.json file and call its classes or methods anywhere I need them.

**Comment by rovillesarate** [comment]
The FPDF package is for generating pdf's.

I can't seem to make it work. Here is what i did : 
- composer require codedge/laravel-fpdf
- I added the alias in the theme.config.php 
- 'Fpdf' => Codedge\Fpdf\Facades\Fpdf::class, 
- I added this to the provider.config.php
- Codedge\Fpdf\FpdfServiceProvider::class,

but even with just this two i am already getting errors 
- Call to undefined method Themosis\Facades\Config::get()

I am trying to test it on the themes using the route;
```
Route::get('/', function (Codedge\Fpdf\Fpdf\Fpdf $fpdf) {

    $fpdf->AddPage();
    $fpdf->SetFont('Courier', 'B', 18);
    $fpdf->Cell(50, 25, 'Hello World!');
    $fpdf->Output();

});
```

**Comment by noxify** [comment]
Hi,

i think the problem is, that you're using a laravel package.

The Themosis Framework is not based on laravel - it uses only some components.

Maybe you should try to use something like https://github.com/Setasign/FPDF (fpdf standalone).

If it's just the missing "Config" Facade, then you can try: https://github.com/keltiecochrane/themosis-illuminate which includes a replacement for the Themosis Config implementation.

But i think there are some more hidden "challenges" ;)
