### ISSUE TITLE
Why should you extend Themosis in a plugin instead of the theme itself?

### ISSUE THREAD

**Issue by bwrice** [themosis/framework#457]
In the docs it states:

> Until now, you wrote code only inside your theme resources directory in order to customize your project. But this has to change.

> Since release 1.3.0, we highly recommend you to develop custom plugins when you intend to extend WordPress and let the theme leverage the display.

What are the drawbacks of simply extending Themosis in the theme itself vs. creating plugins to extend it?

**Comment by jlambe** [comment]
It is our "best practice" advice if you're working with large custom applications built with WordPress. The statement is saying that any "data" features should be defined in a plugin where the theme only handles the display.

This is in order to avoid loosing data access inside the WordPress administration if you happen to switch the theme as well as keeping non used data in the database. For example: you could have write a script to drop data when the plugin is deactivated or deleted, freeing space in your database.

Working with plugins allows you to re-use your work on several projects as well.

But of course you're free to develop any features for your project inside a theme. It's just that we don't recommend it.
