### ISSUE TITLE
Get slug of taxonomy 

### ISSUE THREAD

**Issue by Somesa** [themosis/framework#459]
Hello, i have a custom taxonomy (on a custom post) named "categorie" 

i have 4 categories on it : the-one / the-second / the-third / the-fourth
When have rawrite false on: `Taxonomy::make('categorie'...  ['rewrite'      => false,])`  
And i go on specific category, i have a link like: www.../?categorie=the-one

then i can get the slug of the taxonomy in my route
`
Route::get('tax', ['categorie', function(Input $request){
    $slug = $request->get('categorie');
}]);
`

but when i put `'rewrite'      => true,` i have a link like: www.../categorie/the-one
And i have an empty value for the request

how can i get the slug of this categorie ?
thanks

**Comment by jlambe** [comment]
@Somesa You can't access WordPress query vars when using pretty permalinks as a URL structure because those variables are hidden.

Inside your controller method you have to look into the query variables. By default the method has as parameters the global `$post` and `$query` variables accessibles. Dig into the `$query` (WP_Query) instance and grab your taxonomy term value from there.

```php
Route::get('tax', ['categorie', function (\WP_Post $post, \WP_Query $query) {
    $term = $query->get('categorie');
}]);
```

I haven't tested this but it should be something similar.

**Comment by Somesa** [comment]
thanks a lot !!
