### ISSUE TITLE
template_redirect router issue with Yoast

### ISSUE THREAD

**Issue by simnom** [themosis/framework#491]
Hi!

Couple of things here, one just trying to understand where the file is generated and secondly an issue.  

1) Where does the mu-plugins/themosis-framework/themosis.php file live within the repo?  I've been hunting around but can't seem to put my finger on it.

2) I have an issue when using Yoast with some of the meta data, in particular, the open graph tags not being injected as part of `wp_head()`.

I've narrowed this down, I think, to the priorities assigned to the following:

In `themosis-framework/themosis.php` line 191

`add_action('template_redirect', [$this, 'setRouter'], 20);`

In Yoast - `wp-seo-main.php` line 340

`add_action( 'template_redirect', 'wpseo_frontend_head_init', 999 );`

As far as I can see the Yoast `wpseo_frontend_head_init` function called is never hit because of the `setRouter` request above.  Changing the priority from `20` to `1000` resolves the issue and doesn't appear to have any detrimental effect on any other functionality.

So, just wondering if this is safe to change and where the `themosis.php` file is so I can set up a PR.

**Comment by jlambe** [comment]
What about calling the Yoast function `wpseo_frontend_head_init` sooner.
I won't accept a PR for changing the router priority because on next version it is no longer used and should not be a problem for this case in particular.

I suggest you change it locally on your project only or if you do not want to track the framework dependency in your repo, you can fork the framework, make your changes and require it into your `composer.json` file instead of the official one.

On next version, this should work as expected.

**Comment by simnom** [comment]
Hey,  Sorry I was hunting through the issue late last night and didn't really give it a huge amount of though. 

Of course, I can just remove the action and add it back in my main `theme.php` which works as expected.

Apologies for being so dim.

**Comment by jlambe** [comment]
No problems. Glad it is solved.
