### ISSUE TITLE
Error 403 MAMP PRO

### ISSUE THREAD

**Issue by dabeecher** [themosis/framework#503]
Hello,

I am new to using the Themosis and struggling to get it working locally. I am running this on MAMP pro and using the following in my env.local

`DB_NAME = "my-project-name.local"
DB_USER = "root"
DB_PASSWORD = "root"
DB_HOST = "localhost"
WP_HOME = "http://my-project-name.local/"
WP_SITEURL = "http://my-project-name.local/cms"`

but when navigating to http://my-project-name.local/ I am getting a 403 forbidden. My MAMP is pointing to my-project-name.local/htdocs/

Any help would be appreciated

**Comment by jlambe** [comment]
It sounds like you don't have have permissions on the directory of your project. Here a screenshot of a working mamp pro configuration regarding Apache:

<img width="542" alt="capture d ecran 2018-05-23 a 11 01 03" src="https://user-images.githubusercontent.com/1917490/40414513-b0f7763e-5e78-11e8-9023-2995eac865b8.png">

Hope this help. Otherwise, you can check on [server fault](https://serverfault.com/) forum for server/environment configuration.

**Comment by dabeecher** [comment]
Thanks for getting back to be @jlambe.

My settings are the same as above on MAMP and my folder permissions are set to read/write for everyone but still get the 403 forbidden

**Comment by jlambe** [comment]
Do you use the default port `8888` or have you changed them to `80` ?

**Comment by dabeecher** [comment]
I am using port 80

**Comment by chrisvidal** [comment]
same 403 issue after installing Themosis on MAM PRO.

what I did:

I ran the console command as per the doc `composer create-project themosis/themosis my-project-name`, set up my `.env` file, set the WP SALT KEYS, and create a virtual host for the project `http://et.local`

Anything I missed?
