### ISSUE TITLE
Allow changing button text for fields with buttons

### ISSUE THREAD

**Issue by twosg** [themosis/framework#506]
At first: Congratulations for this awesome work! Themosis should go core :)

I have a little suggestion for the next release:

Allow changing the Button text when adding media fields:

```
$manufacturers = Taxonomy::make('manufacturers', [$customPostType->get('name')], 'Manufacturers', 'Manufacturer')->set([
	'public'             => true,
	'show_in_nav_menus'  => false,
	'hierarchical'       => false,
	'show_tagcloud'      => false
])->addFields([
	Field::text('website'),
	Field::media('logo', [
		'title' => 'Manufacturer Logo',
		'button' => 'Choose Logo',
		'type'  => 'image'
	]),
]);
```

Currently the text is "Add" which somehow was translated to "OK" in my installation. I was confused and thought the field would not render, because the button appeared just before the save button for the tax.

**Comment by jlambe** [comment]
A general option has been added to all fields in order to let a user add custom translations or override core translations. This feature is now in the `develop` branch.

Basically all fields have a `l10n` option where a user can provide key=>value pairs for translations. Core fields use this option so when defining a field, you'll be able to do this:

```php
Field::choice('color', [
    'l10n' => [
        'placeholder' => __('Your translation')
    ]
]);
```
