### ISSUE TITLE
Right model usage

### ISSUE THREAD

**Issue by SamuelMoraesF** [themosis/framework#533]
What is the right usage for models inside Themosis? Should I create just an abstraction layer for internal Wordpress functions, like this:

```php
namespace MyTheme;

class Post extends Model
{
    protected $id;

    public function __construct(int $postId)
    {
        $this->id = $postId;
    }

    public function getTitleAttribute(): string
    {
        return get_the_title($id);
    }
}
```

Or should I create a real Eloquent Model:

```php
namespace MyTheme;

class Post extends Model
{
    protected $table = 'posts';

    protected $primaryKey = 'ID';

    public $timestamps = false;

    public function getTitleAttribute(string $value): string
    {
        return apply_filters('the_title', $value);
    }
}
```
- Should I get a better performance with Wordpress functions? are WP_Post objects and functions like `get_the_title` cached?

- Using the second option, may I have issues with Wordpress database structure updates?

**Comment by jlambe** [comment]
It depends of where you use these models. Generally, if in a default WordPress request, like single post, WordPress has already fetch and construct a WP_Post (model) instance for you. Going with an Eloquent model of your own will make a second request to the database so regarding performance, you're losing a bit.

It's a matter of how you feel. If you're going to perform lots of logic with the data, perhaps you might feel more at home with an Eloquent version with so automatism otherwise if it's just a matter a display post, already fetched data, I tend to stick with a WP_Post instance.

**Comment by SamuelMoraesF** [comment]
My real fear is losing many plugin features when using Eloquent Models(like informations manipulated by WP filters).

How frequently is database structure updates? I'm looking for something like [Corcel](https://github.com/corcel/corcel)

**Comment by jlambe** [comment]
I haven't had the time to explore the Corcel project. I know the author once asked to merge it within the framework but it hasn't worked because on our side we were not fully comptible with the illuminate packages. This is going to clearly change on the next release as we're already compatible with Laravel 5.7.

The database core structure isn't changing that much. The last change I can remember is regarding the terms meta but since then, it hasn't changed (I suppose).

Now by my experience, I haven't yet used a plugin that changes a WP_Post instance structure or data, it often happens right before display so the WP_Post instance stays "pure" if I may say.
