### ISSUE TITLE
How to extend or override classes in 2.0

### ISSUE THREAD

**Issue by twosg** [themosis/framework#604]
Maybe this is a more Laravel question, but I am wondering how to extend or override specific classes within the Themosis namespace.

I tried to do something like this in `App\Providers\AppServiceProvider`:

```
$this->app->when(\Themosis\Forms\FormFactory::class)
	              ->needs(\Themosis\Field\Factory::class)
	              ->give(function () {
		              return \App\Forms\Field\Factory::class;
	              });
```

But it does not seem to change anything. Do I need to provide an own Facade instead of the default one?!

**Comment by jlambe** [comment]
Not sure about your code but in theory providing a custom facade for your factory should work. The form needs fields that implements the `FieldTypeInterface`.

If your doing this in order to provide custom fields, you also not need to use the factory as you can pass an instance of your custom field directly to your form with the `add()` method.
