### ISSUE TITLE
Plugin conflicts

### ISSUE THREAD

**Issue by guramsutidze** [themosis/framework#632]
Hello.

WPML and Yoast SEO Plugins come in conflict on Themosis Framework, resulting a bug in Apperance -> Menus. please find out the reason and get rid of the error, Because, as you know, both of them are very important plugins for WordPress developers.

The reason of error isn't in Themosis Theme, I've personally researched it and found out that the reason is in Themosis Framework.

Version:
Themosis Framework: 2.0-beta3
WPML Multilingual CMS: 4.2.4.1
Yoast SEO: 10.0.1

Console error message:

Uncaught ReferenceError: columns is not defined
    at Object.initToggles (nav-menu.js?ver=5.1.1:600)
    at Object.init (nav-menu.js?ver=5.1.1:66)
    at HTMLDocument.<anonymous> (nav-menu.js?ver=5.1.1:1300)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)

  | initToggles | @ | nav-menu.js?ver=5.1.1:600
-- | -- | -- | --
  | init | @ | nav-menu.js?ver=5.1.1:66
  | (anonymous) | @ | nav-menu.js?ver=5.1.1:1300
  | i | @ | jquery.js?ver=1.12.4:2
  | fireWith | @ | jquery.js?ver=1.12.4:2
  | ready | @ | jquery.js?ver=1.12.4:2
  | K | @ | jquery.js?ver=1.12.4:2

**Comment by jlambe** [comment]
Hi, looking at your posted console error message, there is nothing related to the framework as any of its scripts are represented in your message.

Have you tried to access the menus without the plugins activated to see if it is indeed related to the framework ? I suggest you try to deactivate each plugin and check the menus after each re-activation to see which one might run this issue.

**Comment by guramsutidze** [comment]
I'm not goddamn stupid, I've tried those shits and that's why wrote to you, I've fucked mind on WPML support for a long time until I discovered, that the conflict of plugins happens exactly in Themosis Framework.

Have U tried setting up those two plugins on Themosis Frimework looking inside the menu?

**Comment by jlambe** [comment]
Have you tried to disable core JS assets of the framework by commenting out the assets calls on the `app/Hooks/Application.php` file ? We'll then see if those are conflicting within your application.

**Comment by guramsutidze** [comment]
Separately WPML and Yoast SEO - both work perfect, but problem appears when activating those two together in Apperance -> Menus.

I tried dislabed this in app/Hooks/Application.php, but the same error appears.

Also see my discussion with WPML supporter: https://wpml.org/forums/topic/edit-menus-does-not-work/

**Comment by jlambe** [comment]
I don't know if you're attached to those plugins but if you have already a paid license for WPML, and not for Yoast SEO, perhaps I can recommend you another SEO plugin I personnaly use instead of Yoast: https://wordpress.org/plugins/autodescription/

There is a conflict in some JS files. The fact that Themosis core assets were removed and the issue persist proves the issue isn't coming from the framework. Personnaly I hate working with WPML and always recommend the Polylang plugin instead, same for Yoast SEO. One of those 2 plugins is messing with menu js code and as their assets are compiled, it's hard to locate the issue.

I think you'll be best served by changing the Yoast plugin by the one I recommend above and see if this fix your issue. Wpml support does not bring any clue unfortunately.

**Comment by guramsutidze** [comment]
Thank you very much for advice, but the thing that brought me to you is that i have no that problem without Themosis Framework.

There is conflict in an environment of Themosis Framework (excluding Themosis Theme), and if I were you i'd hold those two environments to compare
1. Host with Themosis:
2. Host without Themosis;
and than I'd set WPML and Yoast SEO on it and started find out what's the reason of that conflict. at least I'd know that thing really happens or that guy (me) is liar or he's doing something wrong
giving alternative advice is very easy way

**Comment by jlambe** [comment]
Have you tried to set the `APP_DEBUG` to `false` in your `.env` file to see how things work ?
Can you also check into the log file stored into `storage/logs` of your application and see if there are any errors reported related to the menus page ?

Because the framework is triggering exceptions on all issues, perhaps a resource has not been loaded by one of the plugin that the nav-menu js file need.

For the time being, I can't test WPML as I don't have a license for it or you can still send a copy of your plugin to "support@themosis.com" and I'll take a look then.

**Comment by jlambe** [comment]
@guramsutidze So one of the two plugins has a bug somewhere in its code base. By default, the framework is catching all errors on local because `APP_DEBUG` is set to `true` for development.

When you deploy your code on production, it is best practice to set `APP_DEBUG` to `false` as all errors and warnings are still reported on the log file.

Perhaps you can explore your application log file and locate the bug related to one of the two plugins and warn them about it.

**Comment by guramsutidze** [comment]
Thanks
