### ISSUE TITLE
Where to put the shortcode functions

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#659]
Hi! Using the new themosis framework version. Where should i put my custom functions? previously putting it inside the app folder would do the trick but for some reason cant make it work now. Does it need to follow a folder structure or should be in a class?

**Comment by jlambe** [comment]
Theme custom functins can be included inside the `inc` directory. All files are autoloaded and can be nested.

Otherwise, if you want to provide global functions from the application root, you can create a file anywhere inside the `app` directory and update your composer.json file to autoload it.

**Comment by rovillesarate** [comment]
Where is the inc directory located?

**Comment by Jaspervv** [comment]
## Theme
If you want to define functions inside your theme, the theme's  `inc` directory would be the best spot.  
All files in this directory are automatically loaded, it's like the `functions.php` in a normal WordPress theme but you can split it into multiple files/directories for better organisation.

## App
You can also add a file inside your App and tell composer to always automatically load this file.
You can name the file anything and place it anywhere, but I'll give you a quick example with a file called "helpers", which is a common practice for providing general helper functions.

### 1. Create the file
Go into your application's `app` directory, and create a file named `helpers.php`. For testing you could add a simple `sayHello` function inside it:
```php
<?php
// app/helpers.php
if( !function_exists('sayHello') ) {
    function sayHello() {
        die('hello from the helpers!');
    }
}
```

### 2. Tell Composer to autoload the file
In the root of your application, open `composer.json` and change the following:
```json
..
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    }
  },
..
```
to:
```json
..
  "autoload": {
    "psr-4": {
      "App\\": "app/"
    },
    "files": [
      "app/helpers.php"
    ]
  },
..
```

### 3. Update the autoloader
Use a terminal to go into your application's root, and run the following command:
```bash
composer dump-autoload
```

### 4. Done!
You should now be able to use the `sayHello()` function anywhere inside your code, and any other functions defined in the file.

**Comment by maximusblade** [comment]
Is step 2 necessary?
according to the documentation... those files are auto loaded .

**Comment by Jaspervv** [comment]
@maximusblade 
According to the documentation the `app` directory is autoloaded by Composer using the [PSR-4 autoloading standard](https://www.php-fig.org/psr/psr-4/), which we know is true because it's in the `composer.json` file.
Using a global `helpers.php` goes against this standard tho, since it doesn't contain a namespace and registers global functions instead of being a class.

Here I see 3 solutions:
## 1. Register it anyway
You might prefer having all your code in the `app` directory, despite the `helpers.php` being against PSR-4 standards. This is pretty common and I don't think it's considered bad practice or anything.  
You'd have to register it in composer.json like I showed before.

## 2. Move it to the bootstrap dir
You could choose to place the helpers in the `bootstrap` directory instead, there's no real difference to this except that your `app` directory will be more consistent. Laravel [does this themselves](https://github.com/laravel/laravel.com/blob/master/bootstrap/helpers.php).  
This would also have to be registered like I showed before, except as `bootstrap/helpers.php` instead of `app/helpers.php`.

## 3. Transform helper to a class
You could also change your helper to a class. For this you'd first create the helper class:
```php
<?php
// ./app/Helper.php

class Helper {
    public static function sayHello() {
        die('hello from helpers!');
    }
}
```
And then register it as an alias inside your `config/app.php`:
```php
// ./config/app.php

    'aliases' => [
        ..
        'Helper' => App\Helper::class,
        ..
    ]
```

Then you can use it anywhere like so:
```php
Helper::sayHello();
```

**Comment by maximusblade** [comment]
Brilliant. thank you. @Jaspervv
