### ISSUE TITLE
What is best practice - business logic in " App" or "Theme" 

### ISSUE THREAD

**Issue by maximusblade** [themosis/framework#661]
I am having difficulty managing Routes that require Session .

What should the core business logic for my application live.

Should I focus on having ALL my routes in the "web.php"

Under what circumstances should I have routes inside my "routes.php" ?

**Comment by Jaspervv** [comment]
The old Themosis way was to have most of your code inside your theme. However since `2.0` Themosis follows a similar/the same structure as Laravel.  

I'd say good practice is to see your root as your application, keep all your logic in there. And let your theme take care of all the visual stuff (styling). That way you could switch theme and not break your application.
Routes are part of the logic, they will often link to Controllers you have inside your root's `app` directory, so I'd register the routes in the root as well.

**Comment by maximusblade** [comment]
@Jaspervv  
Great advice ...thank you
