### ISSUE TITLE
How to handle ajax requests of another plugin

### ISSUE THREAD

**Issue by rovillesarate** [themosis/framework#662]
Hi! I am currently using a plugin called brizy and I am having problems with form submission due to form sending using ajax.

Do i need to make a route or listener to catch the ajax request of the plugin?

**Comment by Jaspervv** [comment]
Generally Ajax requests in WordPress are done with `wp_ajax`, which can be caught with an action (hook): https://codex.wordpress.org/Plugin_API/Action_Reference/wp_ajax_(action)  
You would have to know the name of the action though.

It's also possible the plugin you're speaking of has custom hooks defined, you'd have to check the plugin's documentation or check their source code.

read more about hooks in the [WordPress docs](https://codex.wordpress.org/Plugin_API/Hooks) and the [Themosis docs](https://framework.themosis.com/docs/2.0/hooks/).

**Comment by jlambe** [comment]
If the plugin is managing form submission through Ajax, you need to rely on their documentation in order to hook into it. As @Jaspervv described, ajax requests are sent to a unique URL on a WordPress instance and can be listened to by declaring an action hook.

Ajax requests does not rely then on the routes mechanism and the plugin is ready to go. Perhaps you could describe way more your issue with the form submission. As it is an Ajax request, check the browser console error output and also the response returned by the ajax request inside the "network -> xhr" tool.
