### ISSUE TITLE
[Error] Unresolvable dependency resolving ?

### ISSUE THREAD

**Issue by maximusblade** [themosis/framework#669]
Ive hit an problem on my "dev" environment

I'm trying to load a category listing page.
This works just fine on my development machine.

but I get this error on my dev environment

`Illuminate \ Contracts \ Container \ BindingResolutionException
Unresolvable dependency resolving [Parameter #0 [ <required> $post ]] in class WP_Post`

Why would WP_Post resolve locally....but not on my server?

I have tried composer dump autoload....Ive tried clearing cache...

Anybody else encountered this issue before?

**Comment by Jaspervv** [comment]
try deleting your `./bootstrap/cache/` manually. Usually this is done with `php artisan clear-compiled`, but this command is missing from Themosis's console.

**Comment by tipytechnique** [comment]
Same issue here sometimes. What is the process to fix it with the `./bootstrap/cache/` exactly ?

**Comment by Jaspervv** [comment]
@tipytechnique 
Quite sure dependency injection is cached by Laravel inside one of the `./bootstrap/cache/` files.  

@augustuswm 
Dependency injection doesn't work on WordPress's `\WP_Post` class, because it's constructor takes a `$post` parameter which isn't typed. I can't imagine it ever resolving because of this.  
I think the question lies in why it's trying to resolve it.
