### ISSUE TITLE
Redirection vers la route / (home)

### ISSUE THREAD

**Issue by dimitriBouteille** [themosis/framework#712]
Je viens de tester les deux codes suivants afin de rediriger vers la page d'accueil : 

Depuis le fichier routes/web.php :
```php
Route::redirect('/accueil', '/', 301);
```

Depuis un controller :
```php
return redirect()->route('/', [], 301);

// ou
return redirect()->route('home', [], 301);
```

Dans les deux cas la redirection se fait mais sur l'url `/front` or la redirection devrait être plutôt `/`

Est-ce normal où c'est un bug ? 
Dans le cas où c'est normal, y a-t-il moyen de faire la redirection vers la route `/` directement à l'aide du framework ?

**Comment by Jaspervv** [comment]
I don't speak French so apologies if I misunderstood your issue.

You are specifying that it should redirect to a route, when you do this it looks for a **named route**.  

## '/' route
You tried the following:
```php
return redirect()->route('/', [], 301);
```
### Solution
This won't work because `/` is not a route name, but a location. This would work if it was written like so:
```php
return redirect('/');
```

## 'home' route
You also tried the following:
```php
return redirect()->route('home', [], 301);
```
However the route `home` is a [WordPress conditional tag](https://framework.themosis.com/docs/master/routing/#wordpress-routes) which can't be redirected to.  

### Solution
A solution would be to get the home url, and then redirect to that like so:
```php
$home = config('app.url'); // get home url from .env file
// $home = get_home_url(); // get home url with WordPress function
return redirect($home);
```

**Comment by dimitriBouteille** [comment]
Thanks Jaspervv :) 

I use the first solution (`return redirect('/');`)
