### ISSUE TITLE
Form Field File is missing

### ISSUE THREAD

**Issue by xyNNN** [themosis/framework#725]
Currently I've no possibility to render a form field from type "file" by the re-usable form approach from themosis. Is there a possibility to extend this with custom form types? Or how can I solve this, that I can render this such specific type of form type?

**Comment by jlambe** [comment]
@xyNNN Hello, you will need to create a custom form type for this. Not sure if you have found a solution since you asked but here is base sample:

```php
<?php

namespace App\Fields;

use Themosis\Forms\Contracts\DataTransformerInterface;
use Themosis\Forms\Fields\Types\BaseType;

class FileType extends BaseType implements DataTransformerInterface
{
    public function transform($data){}

    public function reverseTransform($data){}
}
```

I've never looked into a file input so I can't give you more details for now but don't hesitate to come back if you have more implementation questions.

**Comment by xyNNN** [comment]
Thanks @jlambe 
That's what I thought that I've to create a custom file type, thanks! I will figure it out, perhaps I will find time to create a pull request for this missing field type.

**Comment by romainhe** [comment]
someone have any idea about @vasikgreif's question ?
