### ISSUE TITLE
Metabox not saving on update

### ISSUE THREAD

**Issue by vaclavgreif** [themosis/framework#736]
I noticed in the docs:

> In order for a user to save the data handled by the custom fields, each metabox displays a "Save" button below. If the user click on the main "Publish" or "Update" button for the post, the metabox custom fields data will not be saved. Custom fields data is now saved through a custom RestAPI.

That is obviously not a user-friendly design, as I cannot force my users to push two buttons to update a post. This and the inability to add custom metabox fields (#730) makes the whole Metabox functionality basically unusable for me (and possibly others)

Is this going to be fixed in the near future, please? Other than that I love the new UI.

**Comment by jlambe** [comment]
Hello @vasikgreif,

well this is some bold statement regarding the UI is user-friendly or not. I haven't metrics for this so it's hard to tell. But what you need to know is perhaps why I choose to put the UI this way.

WordPress is moving towards ReactJS so in the refactoring of this new version, I started building custom fields that leverage ReactJS too. And as some point, being able to merge better with the next version (understand future) of WordPress. During development, I encounter the issue that React input elements must stay in a "controlled" state with ReactJs in order to fully leverage the library. So indeed I wasn't able to store fields data using the default "Publish/Update" button of WordPress. Then this idea to add a "Save" button per metabox now.

Unfortunately, this won't change right now. But there is probably space for enhancements on this. For example, perhaps we can listen on click events on the "Publish/Update" button as well to perform a behind the scene save action on the fields, or perhaps WordPress has already an API for this (Gutenberg and "classic" metabox), or ...

This is clearly open for discussion and there is still work to do to enhance the custom fields features and UI. I'm open for solutions and ideas 😃 And clearly, if there is a JavaScript champion that reads this, I'll be glad to have advices, reviews or suggestions on the current implementation in order to polish it.

**Comment by vasikgreif** [comment]
Hello,
sorry if the statement was too bold..:) Whan I meant was, that people are used to clicking on one button only to update post. It has been so for years, and it does not make much sense to having to click twice to save one item data.

It would be great to trigger the save on hitting the Update or Publish button. There seems to be some [API](https://github.com/WordPress/gutenberg/pull/7939) already in place for that. Would love to help more, but I'm no way a JS expert...

**Comment by jlambe** [comment]
@vasikgreif no problem. Indeed it seems there is something but need time to dig into source code to find exactly which hook to use in JS.

**Comment by theia-kevin** [comment]
Sorry to bump an ancient topic, but is this in the pipeline, it would be great to be able save all the metaboxes' values attached to a post type at the same time when you update a post.

**Comment by zzkevinlim** [comment]
Bump.

Is this still in the pipeline? It would be nice to be able to update all the metaboxes' values at the same time when you update a post.
