### ISSUE TITLE
Cannot update WP plugins

### ISSUE THREAD

**Issue by joshharington** [themosis/framework#838]
- Themosis Version: 2.0.1
- WordPress Version: 5.8.1
- PHP Version: 7.3.29

### Description
I need to upgrade our client's website from WP 5.8.1 to 5.9. Along with that, I need to update the plugins they use as well.
When updating a standard plugin (Yoast SEO, SVG Support, Duplicator, etc). The first update says it updated successfully, but then if I refresh the page, or try update another plugin, the entire system is bricked with the error "package sentry/sentry is not installed.

### Steps to reproduce
1 - Go to Pluggins -> Installed Pluggins
2 - Update one of the plugins (that has an update). 
3a - Refresh page, or
3b - Update another plugin

### Expected behavior
Error response:
OutOfBoundsException
Package "sentry/sentry" is not installed

----------------
I have tried reinstalling the package in the CLI, but it just throws errors:

```
Problem 1
    - sentry/sentry-laravel 2.x-dev requires sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0, 3.1.1] but these conflict with your requirements or minimum-stability.
    - sentry/sentry-laravel 2.11.0 requires sentry/sdk ^3.1 -> satisfiable by sentry/sdk[3.1.0, 3.1.1] but these conflict with your requirements or minimum-stability.
    - Installation request for sentry/sentry-laravel ^2.11 -> satisfiable by sentry/sentry-laravel[2.11.0, 2.x-dev].
```

**Comment by jlambe** [comment]
@joshharington Unfortunately, this not seems to be a framework issue as packages from "sentry" are not installed by the framework. Those packages seemed to have been required by your own application. The only solution would be to install those missing packages. The required package is a dev package so you should set the `minimum-stability` property to `dev` in your root composer.json file in order to install them or update the required package version to be a `stable` one.

For more support, you can still subscribe on our dedicated platform: [Themosis Support](https://support.themosis.com)
