### ISSUE TITLE
If a page slug is changed, the new path return Page Not Found

### ISSUE THREAD

**Issue by acaron** [themosis/framework#93]
If a page slug is changed, the new path return Page Not Found. If I put back the old slug, the route is working again.

Is there a cache or something? What can I do to refresh and fit to the new path?

Please write it in your documentation if there is something.

**Comment by jlambe** [comment]
Hi,

this is a normal behavior. The `Route` class uses the default WordPress conditional functions. So if you're checking for a specific page route using its `slug` name and you change the slug after in the WordPress admin, it's normal that the page is not found. If you're not sure about the slugs you will use, you can also define the `page title` or the page `id`.

For example:
Let's say I create an "About" page. In WordPress admin, this page will have the following properties:
- Title: `About`
- Slug: `about`
- ID: `42`

For this I could write this route:
```php
Route::get('page', array('about', function()
{
    return "About page content";
}));
```

Now if I change the slug of the page:
- Slug: `about-us`

The actual route won't work because I'm checking a page with a slug of `about`. So in place, I might use the page `ID` so even if I change the slug, the request is still valid/checked:

```php
Route::get('page', array(42, function()
{
    return "About page content";
}));
```

Hope this clarifies your issue.

**Comment by acaron** [comment]
Ok, but why there is no way to force the Route class to update to the new database information? It is kind of a big issue since something like: the project -> project can happen if you work for a client (they change their mind frequently). And even testimg with dummy datas in local environment.

**Comment by acaron** [comment]
If you look for about insteaf of about-us you clearly have a cache or something.

**Comment by acaron** [comment]
And the id thing is not a good idea since ids can change between environment. It is different databases.

**Comment by jlambe** [comment]
But is it the slug or the title your client is changing?

If these are changed permanently, perhaps it is best to use the `template` route in place of the `page` one.

The Route class is an enhanced conditional function so it behaves exactly the same as the core functions. There is no cache available but I suppose the rewrite rules are for something in order to redirect an `about` request to an `about-us`.

**Comment by acaron** [comment]
If the page title is changing, you want to reflect it to the page slug. For example, if I change `about` to `about-us` and I have this code in `routes.php`:
```
Route::get('page',function()
{
    return "Page content";
});
```
When I call `/about-us`, it don't work. I don't want to create template if it is a regular page with the same layout as any other page. The slug just don't update at all if it is changed.

**Comment by acaron** [comment]
I now understand what it is happening! Someone has set a custom post type with the exact same name...  Also, it took a while to Wordpress to empty its cache and display the other one I changed. So, I will transform my issue to a feature to add! It would help if the `No route defined` page can detect if there is something set and give a hint about it like: you can add this route and this view to make the custom post type loop, etc.

**Comment by jlambe** [comment]
:+1: Glad your issue is solved, I was going crazy looking/testing the page route with no issue at all on clean installation ;)
It would be nice but how can we define which custom post type has precedence over the other one?

**Comment by acaron** [comment]
I removed the custom post type and now Wordpress is showing me the front page only... changing browser, emptying cache... not working... If I check out the `is_page` function, the `$page` variable receive "". Wordpress code is a mess. I will try to dig into it!

For the precedence, it can tell you if you have more than one like: You have a problem! ...
And if there's only one, just display the required code. It is an issue with Wordpress too so. But with the framework, it can be a nice addition!

**Comment by acaron** [comment]
Ok, I save the permalinks again and now the page is working! Wordpress... Wordpress...

**Comment by jlambe** [comment]
Perhaps I misunderstood your issue. You had a custom post type with a default slug name of `page` which creates a conflict with the default one? Regarding precedence I'm not sure about the mechanism of WordPress, I think it's an order of rewrite rules but I need to dig more into the core rewrite API.

But sure enough, when you start a new project from scratch, it is best to first activate your theme and then directly set a permalink structure before writing any code so you're good to go.

**Comment by acaron** [comment]
No, I had a page named `les-references` (french) that was changed to `references` which was also a custom post type. I didn't start the project so it was hard to figure out the problem and I just didn't think about the custom post type (I don't know why, it should be my first reaction)... Actually, it is a Wordpress issue where they are not really explaining the Why in development mode (that don't even exists). It can be a great addition to a framework to be more explicit and help solve these types of problems only in development mode.

Do you want me to close this issue and open a feature issue? Tell me if you think it can be done. I'm more thinking about creating my own open-source CMS with Laravel 5. There is a lot of CMS on Laravel, but they only think about the developper and not the user that will actually write the content (usually not a power user or a client). That is the part that Wordpress nailed but the source code... well...

Great work on the framework and thank you for the help!

**Comment by jlambe** [comment]
Yes you can open a ticket for the feature and give some details about what you're looking at. I can't say if it is do-able but we get a record and some people might help too ;)
I'm closing this issue as it is solved. Thanks for using the framework.
